# Lista do analizy wszystkich produktów
links = [
    # Szafy na kartoteki
    ("https://bakpol.pl/szafy-na-kartoteki/797-ska4-2-szafa-kartotekowa.html", "1104", "SZK 101"),
    ("https://bakpol.pl/szafy-na-kartoteki/798-ska4-3-szafa-kartotekowa.html", "1368", "SZK 201"),
    ("https://bakpol.pl/szafy-na-kartoteki/799-ska4-4-szafa-kartotekowa.html", "1632", "SZK 301"),
    ("https://bakpol.pl/meble-biurowe-premium/2069-prska42-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe/2070-prska42x-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2071-prska43-szafa-kartkotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe/2072-prska43x-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe/2073-prska44-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2074-prska44x-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2075-prska45-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2085-prska54xv-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2084-prska54v-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2083-prska54h-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2081-prska53xv-szafka-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2080-prska53v-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2079-prska53h-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2078-prska52xv-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2077-prska52v-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2076-prska45x-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2090-prska57h-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/szafy-biurowe-metalowe/2089-prska56h-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2088-prska55xv-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2087-prska55v-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/meble-biurowe-premium/2086-prska55h-szafa-kartotekowa-premium.html", "", "SZK"),
    ("https://bakpol.pl/szafy-na-kartoteki/2169-ska45-szafa-kartotekowa.html", "", "SZK"),
    ("https://bakpol.pl/szafy-na-kartoteki/2212-ska52v-szafa-kartotekowa.html", "", "SZK"),
    ("https://bakpol.pl/szafy-na-kartoteki/2213-ska53h-szafa-kartotekowa.html", "", "SZK"),
    ("https://bakpol.pl/szafy-na-kartoteki/2214-skb53-szafa-kartotekowa.html", "", "SZK"),
    ("https://bakpol.pl/szafy-na-kartoteki/2215-ska54xv-szafa-kartotekowa.html", "2532", "SZK 305"),
    ("https://bakpol.pl/szafy-na-kartoteki/2216-ska44x-szafa-kartotekowa.html", "2268", "SZK 302"),
    ("https://bakpol.pl/szafy-na-kartoteki/2217-skb55x-szafa-kartotekowa.html", "", "SZK"),
    # Szafy żaluzjowe
    ("https://bakpol.pl/sklep/2202-sz8005-szafa-zaluzjowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-zaluzjowe/2203-sz10005-szafa-zaluzjowa.html", "2688", "SBM 208"),
    ("https://bakpol.pl/szafy-zaluzjowe/2204-sz12006-szafa-zaluzjowa.html", "2952", "SBM 217"),
    ("https://bakpol.pl/szafy-zaluzjowe/2205-kz8005-szafa-zaluzjowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-zaluzjowe/2206-kz10005-szafa-zaluzjowa.html", "2004", "SBM 105"),
    ("https://bakpol.pl/szafy-zaluzjowe/2207-kz12006-szafa-zaluzjowa.html", "2184", "SBM 109"),
    ("https://bakpol.pl/szafy-zaluzjowe/2208-nsz8005-szafa-zaluzjowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-zaluzjowe/2209-nsz10005-szafa-zaluzjowa.html", "1416", "SBM 404"),
    ("https://bakpol.pl/szafy-zaluzjowe/2210-nsz12006-szafa-zaluzjowa.html", "1512", "SBM 406"),
    # Szafy wiszące
    ("https://bakpol.pl/szafy-wiszace/785-ss300-51w-szafa-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/786-nws403-szafka-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/787-nws404-szafka-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/788-nws603-szafka-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/789-nws604-szafka-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/790-nws803-szafka-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/791-nws804-szafka-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/792-nws1004-szafka-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/793-nws1003-szafka-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/794-nws1203-szafka-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/795-nws1204-szafka-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/796-ss300-21w-szafa-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/1304-kn500-4w-szafa-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/1307-kn1000-5-uu-w-szafa-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/1308-ss300-41w-szafa-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/1306-kn1000-6w-szafa-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/1309-nsb700-4w-szafa-wiszaca.html", "", "SKA"),
    ("https://bakpol.pl/szafy-wiszace/1310-kb1000-4w-szafa-wiszaca.html", "", "SKA"),
    # Szafy z drzwiami z pleksi
    ("https://bakpol.pl/szerokosc-skrytki-300-mm/1548-plss300-44-szafa-skrytkowa-z-drzwiami-pleksi.html", "", "SUS PLEXI"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1629-plss400-36-szafa-skrytkowa-z-drzwiami-pleksi.html", "", "SUS PLEXI"),
    ("https://bakpol.pl/szerokosc-skrytki-350-mm/1603-plss350-35-szafa-skrytkowa-z-drzwiami-pleksi.html", "", "SUS PLEXI"),
    # Szafy biurowe metalowe Szafy przesuwne wysokie
    ("https://bakpol.pl/szafy-przesuwne-wysokie/662-sp700-5-szafa-przesuwna.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/663-sp700-4-szafa-przesuwna.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/665-sp700-6-szafa-przesuwna.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/664-sp800-4-szafa-przesuwna.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/666-sp900-4-szafa-przesuwna.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/667-sp800-5-szafa-przesuwna.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/668-sp800-6-szafa-przesuwna.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/669-sp900-5-szafa-przesuwna.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/671-sp900-6-szafa-przesuwna.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/670-sp1000-4-szafa-przesuwna.html", "2520", "SBM 222"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/672-sp1000-6-szafa-przesuwna.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/673-sp1000-5-szafa-przesuwna.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/674-sp1200-5-szafa-przesuwna.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/675-sp1200-4-szafa-przesuwna.html", "2652", "SBM 220"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/676-sp1200-6-szafa-przesuwna.html", "", "SBM"),
    # Szafy biurowe metalowe Szafy przesuwne niskie
    ("https://bakpol.pl/szafy-przesuwne-niskie/677-kp800-4-szafa-przesuwna-niska.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-niskie/679-kp800-6-szafa-przesuwna-niska.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-niskie/678-kp800-5-szafa-przesuwna-niska.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-niskie/680-kp1000-4-szafa-przesuwna-niska.html", "1884", "SBM 112"),
    ("https://bakpol.pl/szafy-przesuwne-niskie/681-kp1000-5-szafa-przesuwna-niska.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-niskie/683-kp1000-6-szafa-przesuwna-niska.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-niskie/682-kp1200-4-szafa-przesuwna.html", "1968", "SBM 110"),
    ("https://bakpol.pl/szafy-przesuwne-niskie/684-kp1200-6-szafa-przesuwna.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-niskie/685-kp1200-5-szafa-przesuwna.html", "", "SBM"),
    ("https://bakpol.pl/szafy-przesuwne-niskie/2306-kp15005-szafa-przesuwna.html", "", "SBM"),
    # Szafy biurowe wysokie
    ("https://bakpol.pl/szafy-biurowe-wysokie/686-sb600-4-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/687-sb600-5-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/689-sb600-6-szafa-biurowa.html", "1476", "SBM 201"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/688-sb700-4-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/690-sb700-5-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/691-sb700-6-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/692-sb800-4-szafa-biurowa.html", "1668", "SBM 202"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/694-sb800-6-szafa-biurowa.html", "1836", "SBM 202"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/695-sb900-4-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/696-sb900-5-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/697-sb900-6-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/698-sb1000-4-szafa-biurowa.html", "1788", "SBM 203"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/699-sb1000-5-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/700-sb1200-4-szafa-biurowa.html", "1968", "SBM 212"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/701-sb1000-6-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/702-sb1200-5-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/703-sb1200-6-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/biurka-krzesla-i-inne/661-rna1200-5-regal-nauczycielski.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-rozne/756-sr600-4-regal-biurowy.html", "1128", "RZ 201"),
    ("https://bakpol.pl/szafy-biurowe-rozne/757-sr800-4-regal-biurowy.html", "1212", "RZ 202"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/2276-sb10005sk-sk20.html", "2148", "SBM 204"),
    # Szafy biurowe niskie
    ("https://bakpol.pl/szafy-biurowe-niskie/704-kb500-4-szafa-biurowa.html", "900", "SBM 101"),
    ("https://bakpol.pl/szafy-biurowe-niskie/705-kb500-5-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-niskie/706-kb500-6-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-niskie/707-kb800-4-szafa-biurowa.html", "1140", "SBM 102"),
    ("https://bakpol.pl/szafy-biurowe-niskie/708-kb800-5-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-niskie/709-kb800-6-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-niskie/710-kb1000-4-szafa-biurowa.html", "1212", "SBM 103"),
    ("https://bakpol.pl/szafy-biurowe-niskie/711-kb1000-5-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-niskie/712-kb1200-5-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-niskie/714-kb1200-4-szafa-biurowa.html", "1296", "SBM 107"),
    ("https://bakpol.pl/szafy-biurowe-niskie/713-kb1000-6-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-niskie/715-kb1200-6-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-niskie/2191-kbs6004-szafa-biurowa-z-szuflada.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-niskie/2192-kbs8004-szafa-biurowa-z-szuflada.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-niskie/2193-kbs10004-szafa-biurowa-z-szuflada.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-niskie/2194-kbsn6004-szafa-biurowa-z-szuflada.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-niskie/2195-kbsn8004-szafa-biurowa-z-szuflada.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-na-nogach/2196-kbsn10004-szafa-biurowa-z-szuflada.html", "", "SBM"),
    # Szafy biurowe pleksi
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/723-psb1000-5-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/724-psb1000-6-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/725-psb1000-4-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/726-psb1200-4-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/727-psb1200-5-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/728-psb1200-6-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/729-psb600-4-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/730-psb600-5-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/731-psb600-6-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/732-psb700-4-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/733-psb700-5-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/734-psb700-6-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/735-psb800-4-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/736-psb800-5-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/737-psb800-6-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/738-psb900-4-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/739-psb900-5-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/740-psb900-6-szafa-z-drzwiami-z-pleksi.html", "", "SBM"),
    # Szafy biurowe na kółkach
    ("https://bakpol.pl/szafy-biurowe-na-kolkach/741-sbk600-5-szafa-na-segregatory.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-na-kolkach/742-sbk700-5-szafa-na-akta.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-na-kolkach/743-sbk800-5-szafa-na-akta.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-na-kolkach/744-sbk900-5-szafa-na-akta.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-na-kolkach/745-sbk1000-5-szafa-na-akta.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-na-kolkach/746-sbk1200-5-szafa-na-akta.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-na-kolkach/747-kbk500-5-szafa-na-akta.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-na-kolkach/748-kbk800-5-szafa-na-akta.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-na-kolkach/749-kbk1000-5-szafa-na-akta.html", "", "SBM"),
    # Szafy biurowe różne
    ("https://bakpol.pl/szafy-biurowe-rozne/750-sb1000-5-sk-szafa-biurowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-rozne/751-sb800-5-s-b-szafa-ubraniowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-rozne/753-sb600-5-soc-szafa-ubraniowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-rozne/752-sb1000-5-s-b-szafa-ubraniowa.html", "2352", "SBM 206"),
    ("https://bakpol.pl/szafy-biurowe-rozne/754-sb800-5-soc-szafa-ubraniowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-rozne/755-sb1000-5-soc-szafa-ubraniowa.html", "", "SBM"),
    ("https://bakpol.pl/szafy-biurowe-rozne/756-sr600-4-regal-biurowy.html", "1128", "RZ 201"),
    ("https://bakpol.pl/szafy-biurowe-rozne/757-sr800-4-regal-biurowy.html", "1212", "RZ 202"),
    ("https://bakpol.pl/szafy-biurowe-rozne/758-sr1000-4-regal-biurowy.html", "1308", "RZ 203"),
    ("https://bakpol.pl/szafy-biurowe-rozne/759-sbo600-4-szafa-biurowo-aktowa.html", "", "RZ"),
    ("https://bakpol.pl/szafy-biurowe-rozne/760-sbo800-4-szafa-biurowo-aktowa.html", "", "RZ"),
    ("https://bakpol.pl/szafy-biurowe-rozne/761-sbo1000-4-szafa-biurowo-aktowa.html", "", "RZ"),
    ("https://bakpol.pl/szafy-biurowe-rozne/762-sbo1200-4-szafa-biurowo-aktowa.html", "", "RZ"),
    ("https://bakpol.pl/szafy-szkolne-kostki/622-k40-kostka.html", "", "SKA"),
    ("https://bakpol.pl/szafy-szkolne-kostki/624-k40p-kostka-z-polka.html", "", "SKA"),
    ("https://bakpol.pl/biurka-krzesla-i-inne/657-sna1000-5-szafa-nauczycielska.html", "", "SBMK"),
    ("https://bakpol.pl/biurka-krzesla-i-inne/658-sna1200-5-szafa-nauczycielska.html", "", "SBMK"),
    # Biurka
    ("https://bakpol.pl/przykladowe-biurka/2009-bl1565abbp3m-biurko-warsztatowe.html", "", ""),
    ("https://bakpol.pl/meble-biurowe/2011-prbl11a-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2012-prbl11b-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2013-prbl11c-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2014-prbl11d-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2015-prbl11e-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2016-prbl11f-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2017-prbl11g-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2021-prbl15apk-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2019-prbl11i-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2020-prbl11j-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2018-prbl11h-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2022-prbl15a-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2023-prbl15af-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2024-prbl15bc-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2025-prbl15b-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2026-prbl15bpk-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2033-prbl15e-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2032-prbl15epk-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2031-prbl15di-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2030-prbl15d-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2029-prbl15dpk-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2028-prbl15c-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2027-prbl15cpk-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2034-prbl15eg-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2035-prbl15fpk-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2036-prbl15f-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe/2037-prbl15gpk-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2038-prbl15g-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2039-prbl15gi-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2040-prbl15hpk-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2041-prbl15h-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2042-prbl15hb-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2043-prbl15ipk-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2044-prbl15i-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2046-prbl15jpk-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2047-prbl15j-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2048-prbl15jc-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2058-prbl20ef-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2056-prbl20dc-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2057-prbl20e-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2054-prbl20cg-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2055-prbl20d-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2050-prbl20ad-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2051-prbl20b-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2052-prbl20bf-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2053-prbl20c-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2049-prbl20a-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2059-prbl20f-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2060-prbl20fi-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2061-prbl20g-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2062-prbl20gb-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2063-prbl20h-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2064-prbl20hd-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2065-prbl20i-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2066-prbl20ie-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2067-prbl20j-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2068-prbl20jd-biurko-premium.html", "", ""),
    ("https://bakpol.pl/meble-biurowe/2198-ks20-stol-konferencyjny.html", "", ""),
    ("https://bakpol.pl/meble-biurowe-premium/2197-ks15-stol-konferencyjny.html", "", ""),
    # Meble specjalistyczne
    ("https://bakpol.pl/wyposazenie-stajni/1852-pjs6506u1paka-jezdziecka-standard.html", "", ""),
    ("https://bakpol.pl/szafy-narciarskie/237-snr400-1-szafa-narciarska.html", "", ""),
    ("https://bakpol.pl/stanowiska-targowe/263-sat01-stanowisko-administracyjno-targowe.html", "", ""),
    ("https://bakpol.pl/szafy-garazowe/1842-sg1000-5-uvw-szafa-garazowa.html", "", ""),
    ("https://bakpol.pl/sklep/2277-szafa-do-segregacji-odpadow.html", "", ""),
    ("https://bakpol.pl/wyposazenie-stajni/2312-prst6506-mala-paka-jezdziecka-prestige.html", "", ""),
    ("https://bakpol.pl/wyposazenie-stajni/2313-prst11065-duza-paka-jezdziecka-prestige.html", "", ""),
    # Meble Warsztatowe
    ("https://bakpol.pl/meble-warsztatowe/1016-bws-stol-z-skladanym-blatem-na-kolkach.html", "", ""),
    ("https://bakpol.pl/platformy-jezdne-na-skrzynki/1003-pt01-platforma-jezdna-na-skrzynki.html", "", ""),
    ("https://bakpol.pl/przykladowe-stoly/2010-tf96lbs11-20adpl45agcdtw2ge2p-zestaw-stolow-warsztatowych-w-ksztalcie-litery-l.html", "", ""),
    ("https://bakpol.pl/stoly-z-oswietleniem/1167-tfs2096lbs20a-d-pl90-a-stol.html", "", ""),
    ("https://bakpol.pl/wozki-serwisowe/1361-swp3-uu-wozek-serwisowy.html", "", ""),
    ("https://bakpol.pl/wozki-platformowe/1386-wp2p-1m2s-wozek-warsztatowy-z-drabinka-na-pojemniki.html", "", ""),
    ("https://bakpol.pl/wozki-transportowe/1368-wt03-wozek-transportowy.html", "", ""),
    ("https://bakpol.pl/tablice-na-narzedzia/1461-tfr600k-wolnostojaca-tablica-na-narzedzia-z-polka.html", "", "Wózek WW"),
    ("https://bakpol.pl/stanowiska-komputerowe/1414-swk00c-stanowisko-komputerowe.html", "", "SMK 2"),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1275-sws1005t-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/wozki-transportowe/1367-wt02g-wozek-transportowy.html", "", ""),
    ("https://bakpol.pl/stoly-z-regulacja-wysokosci/2091-bsr20a-stol-z-regulacja.html", "", ""),
    ("https://bakpol.pl/meble-warsztatowe/2114-rnws6005-regal-magazynowy.html", "", ""),
    ("https://bakpol.pl/stoly-z-regulacja-wysokosci/2199-bsr20a-stol-z-regulacja.html", "", ""),
    ("https://bakpol.pl/stoly-z-regulacja-wysokosci/2200-bsr20a-stol-z-regulacja.html", "", ""),
    ("https://bakpol.pl/stoly-z-regulacja-wysokosci/2201-bsr20a-stol-z-regulacja.html", "", ""),
    ("https://bakpol.pl/regaly-otwarte/2219-rms5005n-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/sklep/2272-tunel-swietlny.html", "", ""),
    ("https://bakpol.pl/szafki-warsztatowe-z-pulpitem/1201-w06pk-i-szafka-warsztatowa-z-pulpitem.html", "", ""),
    ("https://bakpol.pl/szafki-warsztatowe-z-pulpitem/1202-w06pk-j-szafka-warsztatowa-z-pulpitem.html", "", ""),
    ("https://bakpol.pl/szafki-warsztatowe-z-pulpitem/1203-w06pn-a-szafka-warsztatowa-z-pulpitem.html", "", ""),
    ("https://bakpol.pl/szafki-warsztatowe-z-pulpitem/1204-w06pn-b-szafka-warsztatowa-z-pulpitem.html", "", ""),
    ("https://bakpol.pl/szafki-warsztatowe-z-pulpitem/1205-w06pn-c-szafka-warsztatowa-z-pulpitem.html", "", ""),
    ("https://bakpol.pl/szafki-warsztatowe-z-pulpitem/1206-w06pn-d-szafka-warsztatowa-z-pulpitem.html", "", ""),
    ("https://bakpol.pl/szafki-warsztatowe-z-pulpitem/1207-w06pn-e-szafka-warsztatowa-z-pulpitem.html", "", ""),
    ("https://bakpol.pl/szafki-warsztatowe-z-pulpitem/1208-w06pn-f-szafka-warsztatowa-z-pulpitem.html", "", ""),
    ("https://bakpol.pl/szafki-warsztatowe-z-pulpitem/1209-w06pn-g-szafka-warsztatowa-z-pulpitem.html", "", ""),
    ("https://bakpol.pl/szafki-warsztatowe-z-pulpitem/1210-w06pn-h-szafka-warsztatowa-z-pulpitem.html", "", ""),
    ("https://bakpol.pl/szafki-warsztatowe-z-pulpitem/1211-w06pn-i-szafka-warsztatowa-z-pulpitem.html", "", ""),
    ("https://bakpol.pl/szafki-warsztatowe-z-pulpitem/1212-w06pn-j-szafka-warsztatowa-z-pulpitem.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1213-sws1005p-szafa-warsztatowa.html", "", "SWM"),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1214-sws1005jp-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1215-sws1005jj-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1216-sws1005ji-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1217-sws1005jg-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1218-sws1005jf-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1219-sws1005jd-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1234-sws1005dh-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1235-sws1005di-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1236-sws1005dj-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1237-sws1005dp-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1240-sws1005ef-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1243-sws1005eg-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1246-sws1005ep-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1251-sws1005fg-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1252-sws1005fh-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1258-sws1005ge-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1259-sws1005gf-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1262-sws1005gi-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1263-sws1005gj-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1264-sws1005gp-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1265-sws1005h-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1268-sws1005hf-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1270-sws1005hh-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1273-sws1005hp-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-warsztatowe-stojace/1275-sws1005t-szafa-warsztatowa.html", "", ""),
    ("https://bakpol.pl/szafy-na-kolkach/1321-w06-a-wozek-narzedziowy.html", "", ""),
    ("https://bakpol.pl/szafy-na-kolkach/1322-w06-b-wozek-narzedziowy.html", "", ""),
    ("https://bakpol.pl/szafy-na-kolkach/1323-w06-c-wozek-narzedziowy.html", "", ""),
    ("https://bakpol.pl/szafy-na-kolkach/1324-w06-d-wozek-narzedziowy.html", "", ""),
    ("https://bakpol.pl/szafy-na-kolkach/1325-w06-e-wozek-narzedziowy.html", "", ""),
    ("https://bakpol.pl/szafy-na-kolkach/1326-w06-f-wozek-narzedziowy.html", "", ""),
    ("https://bakpol.pl/szafy-na-kolkach/1327-w06-g-wozek-narzedziowy.html", "", ""),
    ("https://bakpol.pl/szafy-na-kolkach/1328-w06-h-wozek-narzedziowy.html", "", ""),
    ("https://bakpol.pl/szafy-na-kolkach/1329-w06-i-wozek-narzedziowy.html", "", ""),
    ("https://bakpol.pl/szafy-na-kolkach/1330-w06-j-wozek-narzedziowy.html", "", ""),
    ("https://bakpol.pl/wozki-narzedziowe/1332-wn09a-aa-wozek-narzedziowy.html", "1716", "WWT 75D"),
    ("https://bakpol.pl/wozki-narzedziowe/1333-wn09a-ab-wozek-narzedziowy.html", "", "WWT"),
    ("https://bakpol.pl/wozki-narzedziowe/1334-wn09a-ac-wozek-narzedziowy.html", "", "WWT"),
    ("https://bakpol.pl/wozki-narzedziowe/1335-wn09a-ad-wozek-narzedziowy.html", "", "WWT"),
    ("https://bakpol.pl/wozki-narzedziowe/1336-wn09a-ae-wozek-narzedziowy.html", "", "WWT"),
    ("https://bakpol.pl/wozki-narzedziowe/1337-wn09a-af-wozek-narzedziowy.html", "", "WWT"),
    ("https://bakpol.pl/wozki-narzedziowe/1338-wn09a-fd-wozek-narzedziowy.html", "", "WWT"),
    ("https://bakpol.pl/wozki-narzedziowe/1341-wn09a-2xc-wozek-narzedziowy.html", "", "WWT"),
    ("https://bakpol.pl/wozki-narzedziowe/1343-wn09a-2xe-wozek-narzedziowy.html", "2232", "WWT 75B"),
    ("https://bakpol.pl/wozki-narzedziowe/1344-wn09a-2xf-wozek-narzedziowy.html", "", "WWT"),
    ("https://bakpol.pl/wozki-narzedziowe/1348-wn09a-aj-wozek-warsztatowy.html", "", "WWT"),
    # Meble Magazynowe
    ("https://bakpol.pl/regaly-specjalistyczne/1820-rw1-15-regal-warsztatowy.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1821-rw1-15k-regal-warsztatowy.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1822-rw1-25-regal-warsztatowy.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1823-rw1-25k-regal-warsztatowy.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1824-rw1-35-regal-warsztatowy.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1825-ro-01s-regal-na-oprawy-narzedziowe.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1826-ro-01p-regal-na-oprawy-narzedziowe.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1827-ro-02n-regal-na-oprawy-narzedziowe.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1828-ro-02k-regal-na-oprawy-narzedziowe.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1834-rmso1005-regal-na-opony.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1830-rw3k-regal-warsztatowy.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1831-rw2n-regal-warsztatowy.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1832-rw3n-regal-warsztatowy.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1833-rw2k-regal-warsztatowy.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1834-rmso1005-regal-na-opony.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1835-rmson1005-regal-na-opony.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1836-rmso-oc-regal-na-opony.html", "", ""),
    ("https://bakpol.pl/regaly-otwarte/1816-rw5-regal-jezdny-na-skrzynki.html", "", ""),
    ("https://bakpol.pl/regaly-zabudowane/1770-regal-narzedziowy-rn-600-4.html", "", ""),
    ("https://bakpol.pl/regaly-zabudowane/1771-regal-narzedziowy-rn-800-4.html", "", ""),
    ("https://bakpol.pl/regaly-zabudowane/1772-regal-narzedziowy-rn-1000-4.html", "", ""),
    ("https://bakpol.pl/regaly-zabudowane/2115-rnws8005-regal-jezdny-z-szafka.html", "", ""),
    ("https://bakpol.pl/regaly-zabudowane/2116-rnws10005-regal-jezdny-z-szafka.html", "", ""),
    ("https://bakpol.pl/regaly-zabudowane/2117-rnws12005-regal-jezdny-z-szafka.html", "", ""),
    ("https://bakpol.pl/szafy-narzedziowe-na-nogach/1764-snn600-4-szafa-narzedziowa.html", "", ""),
    ("https://bakpol.pl/szafy-narzedziowe-na-nogach/1765-snn700-6-szafa-narzedziowa.html", "", ""),
    ("https://bakpol.pl/szafy-narzedziowe-na-nogach/1766-snn900-5-szafa-narzedziowa.html", "", ""),
    ("https://bakpol.pl/szafy-narzedziowe-na-nogach/1767-knn500-6-szafa-narzedziowa.html", "", ""),
    ("https://bakpol.pl/szafy-narzedziowe-na-nogach/1768-knn800-5-szafa-narzedziowa.html", "", ""),
    ("https://bakpol.pl/szafy-narzedziowe-na-nogach/1769-knn1000-6-szafa-narzedziowa.html", "", ""),
    ("https://bakpol.pl/szafki-podblatowe/1753-w06n-h-szafka-podblatowa.html", "", ""),
    ("https://bakpol.pl/wozki-serwisowe/1362-swp3-u-wozek-serwisowy.html", "", ""),
    ("https://bakpol.pl/szafy-narzedziowe-z-tablica-na-narzedzia/1685-tsn1000-5-szafa-z-tablica-narzedziowa.html", "", ""),
    ("https://bakpol.pl/szafy-narzedziowe-z-drzwiami-z-pleksi/1712-pkn1000-5-szafa-z-drzwiami-pleksi.html", "", ""),
    ("https://bakpol.pl/szafy-pojemnikowe/1732-snpa500-3-szafa-narzedziowa.html", "", ""),
    ("https://bakpol.pl/regaly-zabudowane/1770-regal-narzedziowy-rn-600-4.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1829-ro-03-regal-na-oprawy-narzedziowe.html", "", ""),
    ("https://bakpol.pl/szafy-przesuwne-niskie/677-kp800-4-szafa-przesuwna-niska.html", "", ""),
    ("https://bakpol.pl/szafy-biurowe-z-drzwiami-z-pleksi/723-psb1000-5-szafa-z-drzwiami-z-pleksi.html", "", ""),
    ("https://bakpol.pl/szafy-narzedziowe-z-szufladami-wysokie/1694-sn1000-5-uvw-szafa-narzedziowa.html", "", ""),
    ("https://bakpol.pl/regaly-specjalistyczne/1871-sppk-stojak-na-prety.html", "", ""),
    ("https://bakpol.pl/szafy-pojemnikowe/1732-snpa500-3-szafa-narzedziowa.html", "", ""),
    ("https://bakpol.pl/regaly-metalowe/1791-rmsw900-5-regal-metalowy.html", "", ""),
    ("https://bakpol.pl/szafy-do-serwerowni/1856-skn1000-5-szafa-na-serwery.html", "1584", "Szafa serwerowa SBM 203M lx"),
    ("https://bakpol.pl/regaly-ocynkowane/2218-rms5005-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-ocynkowane/2220-rmsw5005-regal-metalowy-ocynkowany.html", "", "RMM"),
    ("https://bakpol.pl/regaly-ocynkowane/2221-rmsw5005n-regal-magazynowy-ocynkowany.html", "", "RMM"),
    ("https://bakpol.pl/regaly-ocynkowane/2222-rms10005.html", "576", "RMM 301"),
    ("https://bakpol.pl/regaly-ocynkowane/2223-rms10005n-regal-metalowy-ocynkowany.html", "", "RMM"),
    ("https://bakpol.pl/regaly-ocynkowane/2224-rmsw10005-regal-metalowy-ocynkowany.html", "", "RMM"),
    ("https://bakpol.pl/regaly-ocynkowane/2225-rmsw10005n-regal-metalowy-ocynkowany.html", "360", "RMM 302"),
    ("https://bakpol.pl/regaly-metalowe/2226-rmsw4003-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2227-rmsw6005-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2228-rmsw7003-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2229-rmsw7004-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2230-rmsw7005-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2231-rmsw-8003-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/sklep/2232-rmsw8004-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2233-rmsw800-5-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2234-rmsw9003-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2235-rmsw9004-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2236-rmsw9005-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2237-rmsw10003-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2238-rmsw10004-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2239-rmsw10005-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2240-rmsw4004n-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2241-rmsw4005n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2242-rmsw5003n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2243-rmsw5004n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2244-rmsw5005n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2245-rmsw6003n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2246-rmsw6004n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2247-rmsw6005n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2248-rmsw7003n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2249-rmsw7004n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2250-rmsw7005n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2251-rmsw8003n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2252-rmsw8004n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2253-rmsw8005n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2254-rmsw9003n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2255-rmsw9004n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2256-rmsw9005n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2257-rmsw10003n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2258-rmsw10004n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-wzmocnione/2259-rmsw10005n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-metalowe/2260-rms10003-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-metalowe/2261-rms10003n-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-metalowe/2262-rms4005-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-metalowe/2263-rms4005n-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-metalowe/2264-rms6005-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-metalowe/2265-rms6005n-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-metalowe/2266-rms8005-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-metalowe/2267-rms8005n-regal-metalowy-niski.html", "", "RMM"),
    ("https://bakpol.pl/regaly-metalowe/2268-rms4003-regal-metalowy.html", "", "RMM"),
    ("https://bakpol.pl/regaly-metalowe/2269-rms4003n-regal-metalowy-niski.html", "", "RMM"),
    # Szafki Fitness
    ("https://bakpol.pl/szerokosc-skrytki-350-mm/1572-ss350-36-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/zestawy-szatniowe/1655-zs6-44-zestaw-szatniowy.html", "", "SZOS"),
    ("https://bakpol.pl/szafy-typ-l/11-l300-12-szafa-ubraniowa.html", "948", "SUL 31"),
    ("https://bakpol.pl/szafy-typ-l/12-l300-22-szafa-ubraniowa.html", "1416", "SUL 32"),
    ("https://bakpol.pl/szafy-typ-l/13-l300-32-szafa-ubraniowa.html", "1944", "SUL 33"),
    ("https://bakpol.pl/szafy-typ-l/14-l300-42-szafa-ubraniowa.html", "2424", "SUL 34"),
    ("https://bakpol.pl/szafy-typ-l/15-l300-52-szafa-ubraniowa.html", "", "SUL"),
    ("https://bakpol.pl/szafy-typ-l/20-lwsl300-52-szafa-na-lawce.html", "", "SUL"),
    ("https://bakpol.pl/szafy-na-lawkach/329-lwsl400-42-szafa-na-lawce.html", "", "SUL"),
    ("https://bakpol.pl/szafy-typ-l/844-lwwl400-22-szafa-na-lawce.html", "", "SUL"),
    ("https://bakpol.pl/szafy-ubraniowe-na-nogach/342-ln400-42-szafa-ubraniowa.html", "", "SUL"),
    ("https://bakpol.pl/szafy-ubraniowe-na-nogach/338-ln400-22-szafa-ubraniowa.html", "1632", "SUL 42"),
    ("https://bakpol.pl/szafy-l/318-l400-12-szafa-ubraniowa.html", "996", "SUL 41"),
    ("https://bakpol.pl/szafy-ubraniowe-na-cokole/245-su300-2-szafa-ubraniowa.html", "972", "SUM 320"),
    ("https://bakpol.pl/szafy-typ-l/319-l400-22-szafa-ubraniowa.html", "1524", "SUL 42"),
    ("https://bakpol.pl/szafy-typ-l/320-l400-32-szafa-ubraniowa.html", "2112", "SUL 43"),
    ("https://bakpol.pl/szafy-typ-l/321-l400-42-szafa-ubraniowa.html", "", "SUL"),
    ("https://bakpol.pl/szafy-dzielone/7-su300-32-szafa-ubraniowa.html", "", "SUS"),
    ("https://bakpol.pl/szkolne-wysokosc-180-cm/447-su300-12-szafa-szkolna.html", "", "SUS"),
    ("https://bakpol.pl/szkolne-wysokosc-180-cm/448-su300-22-szafa-szkolna.html", "", "SUS"),
    ("https://bakpol.pl/szkolne-wysokosc-180-cm/449-su300-42-szafa-szkolna.html", "", "SUS"),
    ("https://bakpol.pl/szkolne-wysokosc-180-cm/450-su300-52-szafa-szkolna.html", "", "SUS"),
    ("https://bakpol.pl/szkolne-wysokosc-180-cm/451-su400-12-szafa-szkolna.html", "", "SUS"),
    ("https://bakpol.pl/szkolne-wysokosc-180-cm/453-su400-32-szafa-szkolna.html", "", "SUS"),
    ("https://bakpol.pl/szkolne-wysokosc-180-cm/455-su400-42-szafa-szkolna.html", "", "SUS"),
    ("https://bakpol.pl/szafy-dzielone/491-sun300-12-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-nogach/496-sun400-32-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-cokole/262-su400-1-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-cokole/264-su400-2-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-cokole/265-su400-3-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-cokole/266-su400-4-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-cokole/267-su400-1-bp-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-cokole/268-su400-2-bp-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-przestronne/269-su400-3-bp-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-cokole/270-su400-4-bp-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-z-drzwiami-z-mdf/241-msu300-2-szafa-z-drzwiami-mdf.html", "1992", "MSUM 320 MDF"),
    ("https://bakpol.pl/szafy-ubraniowe-z-drzwiami-z-siatki/243-ssu300-5-szafa-z-drzwiami-z-siatki.html", "", "SUM"),
    ("https://bakpol.pl/zestawy-szatniowe-premium/410-lws300-4p-szafa-na-lawce.html", "", "SUM"),
    ("https://bakpol.pl/zestawy-szatniowe-premium/415-lws400-3p-szafa-na-lawce.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-cokole/250-su300-2dw-szafa-ubraniowa-z-drzwiami-do-wewnatrz.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-nogach/367-sun300-5-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-premium/407-su300-2-p-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-z-drzwiami-z-pleksi/242-plsu300-2-szafa-z-drzwiami-z-pleksi.html", "", "SUM"),
    ("https://bakpol.pl/szafki-fitness/2305-su300-2-szafa-ubraniowa.html", "", "SUM"),
    # Meble Socjalne
    ("https://bakpol.pl/regaly-na-buty/1844-rb1-800-2p-regal-na-buty.html", "", ""),
    ("https://bakpol.pl/regaly-na-buty/1845-rb1-600-2p-regal-na-buty.html", "", ""),
    ("https://bakpol.pl/regaly-na-buty/1846-rb1-1000-2p-regal-na-buty.html", "", ""),
    ("https://bakpol.pl/regaly-na-buty/1847-rb1-1200-2p-regal-na-buty.html", "", ""),
    ("https://bakpol.pl/regaly-na-buty/1848-rb1-600-3p-regal-na-buty.html", "", ""),
    ("https://bakpol.pl/regaly-na-buty/1849-rb1-800-3p-regal-na-buty.html", "", ""),
    ("https://bakpol.pl/regaly-na-buty/1850-rb1-1000-3p-regal-na-buty.html", "", ""),
    ("https://bakpol.pl/regaly-na-buty/1851-rb1-1200-3p-regal-na-buty.html", "", ""),
    ("https://bakpol.pl/zestawy-szatniowe/1651-zs42-24-zestaw-szatniowy.html", "", "SZOZ"),
    ("https://bakpol.pl/zestawy-szatniowe/1652-zs2222-6666-zestaw-szatniowy.html", "", "SZOZ"),
    ("https://bakpol.pl/zestawy-szatniowe/1653-zs26-44-zestaw-sztaniowy.html", "", "SZOZ"),
    ("https://bakpol.pl/zestawy-szatniowe/1654-zs34-6-zestaw-szatniowy.html", "", "SZOZ"),
    ("https://bakpol.pl/zestawy-szatniowe/1655-zs6-44-zestaw-szatniowy.html", "", "SZOZ"),
    ("https://bakpol.pl/zestawy-szatniowe/1656-zs6-4-zestaw-szatniowy.html", "", "SZOZ"),
    ("https://bakpol.pl/zestawy-szatniowe/1657-zs2-2-zestaw-szatniowy.html", "", "SZOZ"),
    ("https://bakpol.pl/wolnostojace/1660-lw1500a-lawka.html", "612", "ŁSZ 3a"),
    ("https://bakpol.pl/wolnostojace/1662-lw1000b-lawka.html", "1032", "ŁSZ 1"),
    ("https://bakpol.pl/wolnostojace/1659-lw1000a-lawka.html", "1032", "ŁSZ 3"),
    ("https://bakpol.pl/wolnostojace/1663-lw1500b-lawka.html", "1032", "ŁSZ 1a"),
    ("https://bakpol.pl/wolnostojace/1665-lw1000c.html", "", ""),
    ("https://bakpol.pl/lawki-stale/1666-lws320-lawka.html", "", "PWSU"),
    ("https://bakpol.pl/wyposazenie-jadalni/1646-s8-stolik.html", "", ""),
    ("https://bakpol.pl/wyposazenie-jadalni/1647-s12-stolik.html", "", ""),
    ("https://bakpol.pl/wyposazenie-jadalni/1648-krzeslo-sklejka.html", "", ""),
    ("https://bakpol.pl/wyposazenie-jadalni/1650-szafka-sniadaniowa-20-skrytek.html", "", ""),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/2004-ss300122-szafa-wieloskrytkowa.html", "", ""),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/511-ss300-25-szafa-skrytkowa.html", "1764", "SUS 325"),
    ("https://bakpol.pl/szafy-skrytkowe-z-drzwiami-centralnymi/1555-ss300-44c-szafa-skrytkowa-z-drzwiami-centralnymi.html", "", "MKB"),
    ("https://bakpol.pl/szafy-wieloskrytkowe/2179-kd2x56-szafka-wiszaca.html", "", "WSS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/503-ss300-12-szafa-skrytkowa.html", "864", "SUS 312"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/504-ss300-13-szafa-skrytkowa.html", "936", "SUS 313"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/505-ss300-14-szafa-skrytkowa.html", "1008", "SUS 314"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/506-ss300-15-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/507-ss300-16-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/508-ss300-22-szafa-skrytkowa.html", "1428", "SUS 322"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/509-ss300-23-szafa-skrytkowa.html", "1560", "SUS 323"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/510-ss300-24-szafa-skrytkowa.html", "1656", "SUS 324"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/512-ss300-26-szafa-skrytkowa.html", "1872", "SUS 325"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/513-ss300-32-szafa-skrytkowa.html", "2040", "SUS 332"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/514-ss300-33-szafa-skrytkowa.html", "2172", "SUS 333"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/515-ss300-34-szafa-skrytkowa.html", "2304", "SUS 334"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/516-ss300-35-szafa-skrytkowa.html", "2436", "SUS 335"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/517-ss300-36-szafa-skrytkowa.html", "2580", "SUS 336"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/518-ss300-42-szafa-skrytkowa.html", "2628", "SUS 342"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/519-ss300-43-szafa-skrytkowa.html", "2784", "SUS 343"),
    ("https://bakpol.pl/szerokosc-skrytki-300-mm/520-ss300-44-szafa-skrytkowa.html", "2952", "SUS 344"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/521-ss300-45-szafa-skrytkowa.html", "3108", "SUS 345"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/522-ss300-46-szafa-skrytkowa.html", "3276", "SUS 346"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/523-ss350-12-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/524-ss350-13-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/525-ss350-14-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/526-ss350-15-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/527-ss350-16-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/528-ss350-22-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/529-ss350-23-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/530-ss350-25-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/531-ss350-24-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/532-ss350-26-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/533-ss350-32-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/534-ss350-33-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/535-ss350-34-szafa-skrytkowa.html", "", "SUS"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/536-ss400-15-szafa-skrytkowa.html", "1200", "SUS 415"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/537-ss350-35-szafa-skrytkowa.html", "2592", "SUS 435"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/538-ss400-24-szafa-skrytkowa.html", "1936", "SUS 424"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/539-ss400-16-szafa-skrytkowa.html", "1296", "SUS 416"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/540-ss400-25-szafa-skrytkowa.html", "1956", "SUS 425"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/541-ss400-26-szafa-skrytkowa.html", "2064", "SUS 426"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/542-ss400-34-szafa-skrytkowa.html", "2544", "SUS 434"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/543-ss400-35-szafa-skrytkowa.html", "2700", "SUS 435"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/544-ss400-36-szafa-skrytkowa.html", "2844", "SUS 436"),
    ("https://bakpol.pl/szafy-skrytkowe-z-drzwiami-centralnymi/1549-ss300-24c-szafa-skrytkowa-z-drzwiami-centralnymi.html", "", "SUS"),
    ("https://bakpol.pl/szafy-skrytkowe-z-drzwiami-centralnymi/1550-ss300-25c-szafa-skrytkowa-z-drzwiami-centralnymi.html", "", "SUS"),
    ("https://bakpol.pl/szafy-skrytkowe-z-drzwiami-centralnymi/1551-ss300-26c-szafa-skrytkowa-z-drzwiami-centralnymi.html", "", "SUS"),
    ("https://bakpol.pl/szafy-skrytkowe-z-drzwiami-centralnymi/1552-ss300-34c-szafa-skrytkowa-z-drzwiami-centralnymi.html", "", "SUS"),
    ("https://bakpol.pl/szafy-skrytkowe-z-drzwiami-centralnymi/1553-ss300-35c-szafa-skrytkowa-z-drzwiami-centralnymi.html", "", "SUS"),
    ("https://bakpol.pl/szafy-skrytkowe-z-drzwiami-centralnymi/1554-ss300-36c-szafa-skrytkowa-z-drzwiami-centralnymi.html", "", "SUS"),
    ("https://bakpol.pl/szafy-skrytkowe-z-drzwiami-centralnymi/1556-ss300-45c-szafa-skrytkowa-z-drzwiami-centralnymi.html", "", "SUS"),
    ("https://bakpol.pl/szafy-skrytkowe-z-drzwiami-centralnymi/1557-ss300-46c-szafa-skrytkowa-z-drzwiami-centralnymi.html", "", "SUS"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1604-ss400-12-szafa-skrytkowa.html", "960", "MSUS 412S"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1605-ss400-13-szafa-skrytkowa.html", "1044", "SUS 413"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1606-ss400-14-szafa-skrytkowa.html", "1128", "SUS 414"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1609-ss400-22-szafa-skrytkowa.html", "1584", "SUS 422"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1610-ss400-23-szafa-skrytkowa.html", "1716", "SUS 423"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1614-ss400-32-szafa-skrytkowa.html", "2244", "SUS 432"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1615-ss400-33-szafa-skrytkowa.html", "2400", "SUS 433"),
    ("https://bakpol.pl/szafy-gospodarcze-i-na-odziez-brudna/1467-su-w300-1-szafa-na-odziez-brudna.html", "", "MKB"),
    ("https://bakpol.pl/szafy-gospodarcze-i-na-odziez-brudna/1468-su-g300-2-szafa-gospodarcza.html", "1080", "MSU 61"),
    ("https://bakpol.pl/szafy-gospodarcze-i-na-odziez-brudna/1469-su-w400-1-szafa-na-odziez-brudna.html", "1056", "MKB 5E"),
    ("https://bakpol.pl/szafy-gospodarcze-i-na-odziez-brudna/1470-su-g400-2-szafa-gospodarcza.html", "1404", "MSU 81"),
    ("https://bakpol.pl/szafy-gospodarcze-i-na-odziez-brudna/1471-su-g600-1-szafa-socjalna.html", "1080", "MSU 61"),
    ("https://bakpol.pl/szafy-gospodarcze-i-na-odziez-brudna/2106-sgos6005-szafa-gospodarcza.html", "", "MSU Gospodarcze"),
    ("https://bakpol.pl/szafy-gospodarcze-i-na-odziez-brudna/2107-sgos8005-szafa-gospodarcza.html", "1752", "MSU 81"),
    ("https://bakpol.pl/szafy-gospodarcze-i-na-odziez-brudna/2108-sgos10005-szafa-gospodarcza.html", "", "MSU Gospodarcze"),
    ("https://bakpol.pl/szafy-gospodarcze-i-na-odziez-brudna/2109-sgos12005-szafa-gospodarcza.html", "", "MSU Gospodarcze"),
    ("https://bakpol.pl/sklep/2277-szafa-do-segregacji-odpadow.html", "", "MPO"),
    ("https://bakpol.pl/zestawy-strazackie/2427-mstr1006-mobil.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/zestawy-strazackie/2426-strn1200-herse.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/zestawy-strazackie/2421-zestaw-strazacki-beta.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-300/2393-st300ver1.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-300/2394-st300ver1.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-300/2395-st3003.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-300/2396-strn3004.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-300/2397-st3005.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-400/2392-strn4001.html", "876", "SUS 41"),
    ("https://bakpol.pl/szafy-szerokosci-400/2399-strn4002.html", "1296", "SUS 42"),
    ("https://bakpol.pl/szafy-szerokosci-400/2400-strn4003.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-400/2401-strn4004.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/zestawy-strazackie/2398-strn700-camea.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/zestawy-strazackie/2402-strn700-kalipso.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/zestawy-strazackie/2425-strn900-febe.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/zestawy-strazackie/2424-strn1000-atlas.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/zestawy-strazackie/2420-zestaw-strazacki-alfa.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/zestawy-strazackie/2422-zestaw-strazacki-gamma.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/zestawy-strazackie/2423-zestaw-strazacki-delta.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-300/2428-strn3001j.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-300/2430-strn3002j.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-300/2432-strn3003j.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-300/2434-strn3004j.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-300/2436-strn3005j.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-400/2429-strn3001j.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-400/2431-strn3002j.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-400/2433-strn4003j.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-strazackie/2435-strn4004j.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/zestawy-strazackie/2437-strn1000-fobos.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/zestawy-strazackie/2438-zestaw-strazacki-kappa.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-300/2439-strn3001-wen.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-300/2440-strn3002-wen.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-300/2441-strn3003-wen.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-300/2442-strn3004-wen.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-300/2443-strn3005-wen.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-400/2444-strn4001-wen.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-400/2445-strn4002-wen.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-400/2446-strn4003-wen.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-400/2447-strn4004-wen.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/zestawy-strazackie/2448-strsb1000.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/zestawy-strazackie/2449-strsb1200.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-400/2450-strn4001h.html", "876", "SUS 41"),
    ("https://bakpol.pl/szafy-szerokosci-400/2451-strn4002h.html", "1296", "SUS 42"),
    ("https://bakpol.pl/szafy-szerokosci-400/2452-strn4003h.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/szafy-szerokosci-400/2453-strn4004h.html", "", "SUS Strażacki"),
    ("https://bakpol.pl/lawki-strazackie/2454-lwstr1000a30-lawka.html", "", "ŁSZ"),
    ("https://bakpol.pl/lawki-strazackie/2455-lwstr1500a30-lawka.html", "", "ŁSZ"),
    ("https://bakpol.pl/lawki-strazackie/2456-lwstr2000a30-lawka.html", "", "ŁSZ"),
    ("https://bakpol.pl/lawki-strazackie/2457-lwstr1000b30-lawka.html", "", "SZOS"),
    ("https://bakpol.pl/lawki-strazackie/2458-lwstr1500b30-lawka.html", "", "SZOS"),
    ("https://bakpol.pl/lawki-strazackie/2459-lwstr2000b30-lawka.html", "", "SZOS"),
    ("https://bakpol.pl/lawki-strazackie/2460-lwstr1000b30x2-lawka.html", "", "SZOS"),
    ("https://bakpol.pl/lawki-strazackie/2461-lwstr1500b30x2-lawka.html", "", "SZOS"),
    ("https://bakpol.pl/lawki-strazackie/2462-lwstr2000b30x2-lawka.html", "", "SZOS"),
    # SZAFY UBRANIOWE
    ("https://bakpol.pl/zestawy-szatniowe-premium/416-lws400-4p-szafa-na-lawce.html", "", "SUM"),
    ("https://bakpol.pl/szafy-na-lawkach/473-lws300-42-szafa-lawka-daszek.html", "", "SUM"),
    ("https://bakpol.pl/szafy-z-daszkiem-skosnym/2270-su4002d-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-z-daszkiem-skosnym/2271-su3005d-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafki-fitness/2281-lws30042-szafa-lawka.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-bez-cokolu/257-su300-4bc-szafa-ubraniowa-bez-cokolu.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-bez-cokolu/259-su300-5bc-szafa-ubraniowa-bez-cokolu.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-bez-cokolu/271-su400-1bc-szafa-ubraniowa-bez-cokolu.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-nogach/342-ln400-42-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-nogach/343-sw300-1-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-nogach/344-sw300-2-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-nogach/345-sw300-3-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-nogach/346-sw300-4-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-ubraniowe-na-nogach/347-sw300-5-szafa-ubraniowa.html", "", "SUM"),
    ("https://bakpol.pl/szafy-z-daszkiem-skosnym/2274-su3002d-szafa-ubraniowa-daszek.html", "", "SUM"),
    ("https://bakpol.pl/szafy-szkolne/2110-sn6005wf-szafa-gospodarcza.html", "", "SBM Sportowa"),
    ("https://bakpol.pl/szafy-szkolne/2111-sn8005wf-szafa-na-sprzet-sportowy.html", "", "SBM Sportowa"),
    ("https://bakpol.pl/szafy-szkolne/2112-sn10005wf-szafa-na-sprzet-sportowy.html", "", "SBM Sportowa"),
    ("https://bakpol.pl/szafy-szkolne/2113-sn12005wf-szafa-na-sprzet-sportowy.html", "", "SBM Sportowa"),
    ("https://bakpol.pl/szafy-na-laptopy/2180-sl10-szafka-na-laptopy.html", "", "SZNL"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm-dzielone/277-su300-12n-szafa-szkolna.html", "", "MSUSS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm-dzielone/278-su300-22n-szafa-szkolna.html", "", "MSUSS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm-dzielone/279-su300-32n-szafa-szkolna.html", "", "MSUSS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm-dzielone/280-su300-42n-szafa-szkolna.html", "", "MSUSS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm-dzielone/281-su300-52n-szafa-szkolna.html", "", "MSUSS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm-dzielone/282-su400-22n-szafa-szkolna.html", "", "MSUSS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm-dzielone/283-su400-12n-szafa-szkolna.html", "", "MSUSS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm-dzielone/284-su400-32n-szafa-szkolna.html", "", "MSUSS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm-dzielone/285-su400-42n-szafa-szkolna.html", "", "MSUSS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm/291-su400-1n-szafa-szkolna.html", "", "MSUMS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm/292-su400-2n-szafa-szkolna.html", "", "MSUMS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm/293-su400-3n-szafa-szkolna.html", "", "MSUMS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm/294-su400-4n-szafa-szkolna.html", "", "MSUMS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm/438-su300-1n-szafa-szkolna.html", "", "MSUMS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm/439-su300-2n-szafa-szkolna.html", "", "MSUMS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm/440-su300-3n-szafa-szkolna.html", "", "MSUMS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm/441-su300-4n-szafa-szkolna.html", "", "MSUMS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm/442-su300-5n-szafa-szkolna.html", "", "MSUMS"),
    ("https://bakpol.pl/przedszkolne-szkolne-klasy-1-3/420-pss300-13-szafa-dla-dzieci.html", "", "MSUSS"),
    ("https://bakpol.pl/przedszkolne-szkolne-klasy-1-3/421-pss300-23-szafa-dla-dzieci.html", "", "MSUSS"),
    ("https://bakpol.pl/przedszkolne-szkolne-klasy-1-3/422-pss300-33-szafa-dla-dzieci.html", "", "MSUSS"),
    ("https://bakpol.pl/przedszkolne-szkolne-klasy-1-3/423-pss300-43-szafa-dla-dzieci.html", "", "MSUSS"),
    ("https://bakpol.pl/przedszkolne-szkolne-klasy-1-3/424-psu300-11-szafa-dla-dzieci.html", "", "MSUSS"),
    ("https://bakpol.pl/przedszkolne-szkolne-klasy-1-3/425-psu300-21-szafa-dla-dzieci.html", "", "MSUSS"),
    ("https://bakpol.pl/przedszkolne-szkolne-klasy-1-3/426-psu300-31-szafa-dla-dzieci.html", "", "MSUSS"),
    ("https://bakpol.pl/przedszkolne-szkolne-klasy-1-3/427-psu300-41-szafa-dla-dzieci.html", "", "MSUSS"),
    ("https://bakpol.pl/przedszkolne-szkolne-klasy-1-3/428-psu300-51-szafa-dla-dzieci.html", "", "MSUSS"),
    ("https://bakpol.pl/biurka-krzesla-i-inne/659-rna425-5-regal-nauczycielski.html", "", "SBMK"),
    ("https://bakpol.pl/biurka-krzesla-i-inne/660-rna810-5-regal-nauczycielski.html", "", "SBMK"),
    ("https://bakpol.pl/biurka-krzesla-i-inne/661-rna1200-5-regal-nauczycielski.html", "", "SBMK"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm-dzielone/2307-su30012nklon-szafa-szkolna.html", "", "MSUSS"),
    ("https://bakpol.pl/szkolne-wysokosc-150-cm-dzielone/2308-su30022nklon-szafa-szkolna.html", "", "MSUSS"),
    # Wózki warsztatowe>Wózki narzędziowe
    ("https://bakpol.pl/wozki-narzedziowe/1347-wn09a-ah-wozek-warsztatowy.html", "2508", "SZWN 251"),
    ("https://bakpol.pl/wozki-narzedziowe/1356-wn09a-ih-wozek-warsztatowy.html", "2508", "SZWN 252"),
    ("https://bakpol.pl/wozki-narzedziowe/1332-wn09a-aa-wozek-narzedziowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1333-wn09a-ab-wozek-narzedziowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1334-wn09a-ac-wozek-narzedziowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1335-wn09a-ad-wozek-narzedziowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1336-wn09a-ae-wozek-narzedziowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1337-wn09a-af-wozek-narzedziowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1338-wn09a-fd-wozek-narzedziowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1339-wn09a-2xa-wozek.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1340-wn09a-2xb-wozek.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1341-wn09a-2xc-wozek-narzedziowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1342-wn09a-2xd-wozek.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1343-wn09a-2xe-wozek-narzedziowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1344-wn09a-2xf-wozek-narzedziowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1345-wn09a-ai-wozek-warsztatowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1346-wn09a-ag-wozek-warsztatowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1348-wn09a-aj-wozek-warsztatowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1349-wn09a-2xg-wozek.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1350-wn09a-bj-wozek-warsztatowy.html", "3", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1351-wn09a-cg-wozek-warsztatowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1352-wn09a-eb-wozek-warsztatowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1353-wn09a-fc-wozek-warsztatowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1354-wn09a-gd-wozek-warsztatowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1355-wn09a-ia-wozek-warsztatowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1356-wn09a-ih-wozek-warsztatowy.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1357-wn09a-2xh-wozek.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1358-wn09a-2xi-wozek.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1359-wn09a-2xj-wozek.html", "", "SZWN"),
    ("https://bakpol.pl/wozki-narzedziowe/1360-ws-wozek-stanowiskowy.html", "", "SZWN"),
]

# Lista do analizy odpowiedników
links = [
    ("https://bakpol.pl/szafy-na-kartoteki/797-ska4-2-szafa-kartotekowa.html", "1104", "SZK 101"),
    ("https://bakpol.pl/szafy-na-kartoteki/798-ska4-3-szafa-kartotekowa.html", "1368", "SZK 201"),
    ("https://bakpol.pl/szafy-na-kartoteki/799-ska4-4-szafa-kartotekowa.html", "1632", "SZK 301"),
    ("https://bakpol.pl/szafy-na-kartoteki/2215-ska54xv-szafa-kartotekowa.html", "2532", "SZK 305"),
    ("https://bakpol.pl/szafy-na-kartoteki/2216-ska44x-szafa-kartotekowa.html", "2268", "SZK 302"),
    ("https://bakpol.pl/szafy-zaluzjowe/2203-sz10005-szafa-zaluzjowa.html", "2688", "SBM 208"),
    ("https://bakpol.pl/szafy-zaluzjowe/2204-sz12006-szafa-zaluzjowa.html", "2952", "SBM 217"),
    ("https://bakpol.pl/szafy-zaluzjowe/2206-kz10005-szafa-zaluzjowa.html", "2004", "SBM 105"),
    ("https://bakpol.pl/szafy-zaluzjowe/2207-kz12006-szafa-zaluzjowa.html", "2184", "SBM 109"),
    ("https://bakpol.pl/szafy-zaluzjowe/2209-nsz10005-szafa-zaluzjowa.html", "1416", "SBM 404"),
    ("https://bakpol.pl/szafy-zaluzjowe/2210-nsz12006-szafa-zaluzjowa.html", "1512", "SBM 406"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/670-sp1000-4-szafa-przesuwna.html", "2520", "SBM 222"),
    ("https://bakpol.pl/szafy-przesuwne-wysokie/675-sp1200-4-szafa-przesuwna.html", "2652", "SBM 220"),
    ("https://bakpol.pl/szafy-przesuwne-niskie/680-kp1000-4-szafa-przesuwna-niska.html", "1884", "SBM 112"),
    ("https://bakpol.pl/szafy-przesuwne-niskie/682-kp1200-4-szafa-przesuwna.html", "1968", "SBM 110"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/689-sb600-6-szafa-biurowa.html", "1476", "SBM 201"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/692-sb800-4-szafa-biurowa.html", "1668", "SBM 202"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/694-sb800-6-szafa-biurowa.html", "1836", "SBM 202"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/698-sb1000-4-szafa-biurowa.html", "1788", "SBM 203"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/700-sb1200-4-szafa-biurowa.html", "1968", "SBM 212"),
    ("https://bakpol.pl/szafy-biurowe-rozne/756-sr600-4-regal-biurowy.html", "1128", "RZ 201"),
    ("https://bakpol.pl/szafy-biurowe-rozne/757-sr800-4-regal-biurowy.html", "1212", "RZ 202"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/2276-sb10005sk-sk20.html", "2148", "SBM 204"),
    ("https://bakpol.pl/szafy-biurowe-niskie/704-kb500-4-szafa-biurowa.html", "900", "SBM 101"),
    ("https://bakpol.pl/szafy-biurowe-niskie/707-kb800-4-szafa-biurowa.html", "1140", "SBM 102"),
    ("https://bakpol.pl/szafy-biurowe-niskie/710-kb1000-4-szafa-biurowa.html", "1212", "SBM 103"),
    ("https://bakpol.pl/szafy-biurowe-niskie/714-kb1200-4-szafa-biurowa.html", "1296", "SBM 107"),
    ("https://bakpol.pl/szafy-biurowe-rozne/752-sb1000-5-s-b-szafa-ubraniowa.html", "2352", "SBM 206"),
    ("https://bakpol.pl/szafy-biurowe-rozne/756-sr600-4-regal-biurowy.html", "1128", "RZ 201"),
    ("https://bakpol.pl/szafy-biurowe-rozne/757-sr800-4-regal-biurowy.html", "1212", "RZ 202"),
    ("https://bakpol.pl/szafy-biurowe-rozne/758-sr1000-4-regal-biurowy.html", "1308", "RZ 203"),
    ("https://bakpol.pl/tablice-na-narzedzia/1461-tfr600k-wolnostojaca-tablica-na-narzedzia-z-polka.html", "",
     "Wózek WW"),
    ("https://bakpol.pl/stanowiska-komputerowe/1414-swk00c-stanowisko-komputerowe.html", "", "SMK 2"),
    ("https://bakpol.pl/wozki-narzedziowe/1332-wn09a-aa-wozek-narzedziowy.html", "1716", "WWT 75D"),
    ("https://bakpol.pl/wozki-narzedziowe/1343-wn09a-2xe-wozek-narzedziowy.html", "2232", "WWT 75B"),
    ("https://bakpol.pl/szafy-do-serwerowni/1856-skn1000-5-szafa-na-serwery.html", "1584",
     "Szafa serwerowa SBM 203M lx"),
    ("https://bakpol.pl/regaly-ocynkowane/2225-rmsw10005n-regal-metalowy-ocynkowany.html", "360", "RMM 302"),
    ("https://bakpol.pl/szafy-typ-l/11-l300-12-szafa-ubraniowa.html", "948", "SUL 31"),
    ("https://bakpol.pl/szafy-typ-l/12-l300-22-szafa-ubraniowa.html", "1416", "SUL 32"),
    ("https://bakpol.pl/szafy-typ-l/13-l300-32-szafa-ubraniowa.html", "1944", "SUL 33"),
    ("https://bakpol.pl/szafy-typ-l/14-l300-42-szafa-ubraniowa.html", "2424", "SUL 34"),
    ("https://bakpol.pl/szafy-ubraniowe-na-nogach/338-ln400-22-szafa-ubraniowa.html", "1632", "SUL 42"),
    ("https://bakpol.pl/szafy-l/318-l400-12-szafa-ubraniowa.html", "996", "SUL 41"),
    ("https://bakpol.pl/szafy-ubraniowe-na-cokole/245-su300-2-szafa-ubraniowa.html", "972", "SUM 320"),
    ("https://bakpol.pl/szafy-typ-l/319-l400-22-szafa-ubraniowa.html", "1524", "SUL 42"),
    ("https://bakpol.pl/szafy-typ-l/320-l400-32-szafa-ubraniowa.html", "2112", "SUL 43"),
    ("https://bakpol.pl/wolnostojace/1660-lw1500a-lawka.html", "612", "ŁSZ 3a"),
    ("https://bakpol.pl/wolnostojace/1662-lw1000b-lawka.html", "1032", "ŁSZ 1"),
    ("https://bakpol.pl/wolnostojace/1659-lw1000a-lawka.html", "1032", "ŁSZ 3"),
    ("https://bakpol.pl/wolnostojace/1663-lw1500b-lawka.html", "1032", "ŁSZ 1a"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/511-ss300-25-szafa-skrytkowa.html", "1764", "SUS 325"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/503-ss300-12-szafa-skrytkowa.html", "864", "SUS 312"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/504-ss300-13-szafa-skrytkowa.html", "936", "SUS 313"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/505-ss300-14-szafa-skrytkowa.html", "1008", "SUS 314"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/508-ss300-22-szafa-skrytkowa.html", "1428", "SUS 322"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/509-ss300-23-szafa-skrytkowa.html", "1560", "SUS 323"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/510-ss300-24-szafa-skrytkowa.html", "1656", "SUS 324"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/512-ss300-26-szafa-skrytkowa.html", "1872", "SUS 325"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/513-ss300-32-szafa-skrytkowa.html", "2040", "SUS 332"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/514-ss300-33-szafa-skrytkowa.html", "2172", "SUS 333"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/515-ss300-34-szafa-skrytkowa.html", "2304", "SUS 334"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/516-ss300-35-szafa-skrytkowa.html", "2436", "SUS 335"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/517-ss300-36-szafa-skrytkowa.html", "2580", "SUS 336"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/518-ss300-42-szafa-skrytkowa.html", "2628", "SUS 342"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/519-ss300-43-szafa-skrytkowa.html", "2784", "SUS 343"),
    ("https://bakpol.pl/szerokosc-skrytki-300-mm/520-ss300-44-szafa-skrytkowa.html", "2952", "SUS 344"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/521-ss300-45-szafa-skrytkowa.html", "3108", "SUS 345"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/522-ss300-46-szafa-skrytkowa.html", "3276", "SUS 346"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/536-ss400-15-szafa-skrytkowa.html", "1200", "SUS 415"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/537-ss350-35-szafa-skrytkowa.html", "2592", "SUS 435"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/538-ss400-24-szafa-skrytkowa.html", "1936", "SUS 424"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/539-ss400-16-szafa-skrytkowa.html", "1296", "SUS 416"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/540-ss400-25-szafa-skrytkowa.html", "1956", "SUS 425"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/541-ss400-26-szafa-skrytkowa.html", "2064", "SUS 426"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/542-ss400-34-szafa-skrytkowa.html", "2544", "SUS 434"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/543-ss400-35-szafa-skrytkowa.html", "2700", "SUS 435"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/544-ss400-36-szafa-skrytkowa.html", "2844", "SUS 436"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1604-ss400-12-szafa-skrytkowa.html", "960", "MSUS 412S"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1605-ss400-13-szafa-skrytkowa.html", "1044", "SUS 413"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1606-ss400-14-szafa-skrytkowa.html", "1128", "SUS 414"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1609-ss400-22-szafa-skrytkowa.html", "1584", "SUS 422"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1610-ss400-23-szafa-skrytkowa.html", "1716", "SUS 423"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1614-ss400-32-szafa-skrytkowa.html", "2244", "SUS 432"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1615-ss400-33-szafa-skrytkowa.html", "2400", "SUS 433"),
    ("https://bakpol.pl/szafy-gospodarcze-i-na-odziez-brudna/1468-su-g300-2-szafa-gospodarcza.html", "1080", "MSU 61"),
    ("https://bakpol.pl/szafy-gospodarcze-i-na-odziez-brudna/1469-su-w400-1-szafa-na-odziez-brudna.html", "1056",
     "MKB 5E"),
    ("https://bakpol.pl/szafy-gospodarcze-i-na-odziez-brudna/1470-su-g400-2-szafa-gospodarcza.html", "1404", "MSU 81"),
    ("https://bakpol.pl/szafy-gospodarcze-i-na-odziez-brudna/1471-su-g600-1-szafa-socjalna.html", "1080", "MSU 61"),
    ("https://bakpol.pl/szafy-gospodarcze-i-na-odziez-brudna/2107-sgos8005-szafa-gospodarcza.html", "1752", "MSU 81"),
    ("https://bakpol.pl/szafy-szerokosci-400/2392-strn4001.html", "876", "SUS 41"),
    ("https://bakpol.pl/szafy-szerokosci-400/2399-strn4002.html", "1296", "SUS 42"),
    ("https://bakpol.pl/szafy-szerokosci-400/2450-strn4001h.html", "876", "SUS 41"),
    ("https://bakpol.pl/szafy-szerokosci-400/2451-strn4002h.html", "1296", "SUS 42"),
    ("https://bakpol.pl/wozki-narzedziowe/1347-wn09a-ah-wozek-warsztatowy.html", "2508", "SZWN 251"),
    ("https://bakpol.pl/wozki-narzedziowe/1356-wn09a-ih-wozek-warsztatowy.html", "2508", "SZWN 252"),
]

# Lista do analizy przekrojowej
links = [
    ("https://bakpol.pl/szafy-biurowe-wysokie/692-sb800-4-szafa-biurowa.html", "1668", "SBM 202"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/694-sb800-6-szafa-biurowa.html", "1836", "SBM 202"),
    ("https://bakpol.pl/szafy-biurowe-wysokie/698-sb1000-4-szafa-biurowa.html", "1788", "SBM 203"),
    ("https://bakpol.pl/szafy-typ-l/12-l300-22-szafa-ubraniowa.html", "1416", "SUL 32W"),
    ("https://bakpol.pl/szafy-ubraniowe-na-nogach/338-ln400-22-szafa-ubraniowa.html", "1632", "SUL 42W"),
    ("https://bakpol.pl/szafy-ubraniowe-na-cokole/245-su300-2-szafa-ubraniowa.html", "972", "SUM 320W"),
    ("https://bakpol.pl/szafy-typ-l/319-l400-22-szafa-ubraniowa.html", "1524", "SUL 42W"),
    ("https://bakpol.pl/szafy-szkolne-skrytkowe/508-ss300-22-szafa-skrytkowa.html", "1428", "SUS 322W"),
    ("https://bakpol.pl/szerokosc-skrytki-400-mm/1609-ss400-22-szafa-skrytkowa.html", "1584", "SUS 422W"),
]