links = [
# Biurowe
    ("https://jannowak.com/29-szafa-metalowa-alex-szara-aktowa", "", "SBM"),
    ("https://jannowak.com/66-szafa-metalowa-kevin-szara", "", "SBM"),
    ("https://jannowak.com/1-szafa-metalowa-jan-szara", "", "SBM"),
    ("https://jannowak.com/20-szafa-metalowa-jan-ii-szara", "", "SBM"),
    ("https://jannowak.com/8-szafa-metalowa-jan-h-szara", "891", "SBM 202"),
    ("https://jannowak.com/85-szafa-metalowa-wiola-szara-aktowa", "", "SBMK"),
    ("https://jannowak.com/116-szafa-metalowa-edmund-szara", "", "SBMK"),
    ("https://jannowak.com/89-szafa-metalowa-szara-medyczna", "778", "SML 112"),
    ("https://jannowak.com/180-szafa-metalowa-nadstawka-ewa-szara", "322", "SBM 402"),
    ("https://jannowak.com/45-szafa-metalowa-beata-szara", "647", "SBM 103"),
    ("https://jannowak.com/39-szafa-metalowa-damian-szara", "1054", "SBM 208"),
    ("https://jannowak.com/54-szafa-metalowa-kuba-szara", "778", "SBM 222"),
    ("https://jannowak.com/53-szafa-metalowa-magda-szara", "", "SBM"),
    ("https://jannowak.com/94-szafa-metalowa-borys-szara", "973", "SBM 206"),
    ("https://jannowak.com/127-szafa-metalowa-sara-szara-kartotekowa", "526", "SZK 201"),
    ("https://jannowak.com/134-szafa-metalowa-sara-szara-kartotekowa", "810", "SZK 301/5"),
    ("https://jannowak.com/174-szafa-metalowa-dawid-szara-socjalna", "810", "SBM 206"),
    ("https://jannowak.com/178-szafa-metalowa-oliver-szara-socjalna", "1257", "MKB 2"),
    ("https://jannowak.com/215-zestaw-jan-ewa-szary", "", "SBM"),
    ("https://jannowak.com/131-szafa-metalowa-sara-szara-kartotekowa", "647", "SZK 301"),
    ("https://jannowak.com/77-szafa-metalowa-filip-szara-z-sejfem", "973", "SML 114"),
    ("https://jannowak.com/23-szafa-metalowa-daniel-szara-zamek-elektroniczny", "", "SBM"),
    ("https://jannowak.com/59-szafa-metalowa-tomasz-szara-ze-schowkiem", "810", "SBM 204"),
    ("https://jannowak.com/80-szafa-metalowa-filip-ii-szara-z-sejfem", "", "SBM"),
    ("https://jannowak.com/179-szafa-metalowa-lena-szara", "", "SBM"),
    ("https://jannowak.com/184-szafa-metalowa-regal-maks-szara", "485", "RZ 202"),
    ("https://jannowak.com/168-szafa-metalowa-adam-szara-socjalna", "", "MSU Gospodarcze"),
    ("https://jannowak.com/119-szafa-metalowa-kacper-ii-szara-socjalna", "810", "SUM 320"),
    ("https://jannowak.com/120-szafa-metalowa-kacper-szara-socjalna", "891", "SUM 420"),
    ("https://jannowak.com/176-szafa-metalowa-socjalna-julia-szara", "647", "SUL 42"),
    ("https://jannowak.com/111-szafa-metalowa-igor-szara", "973", "SUS 332"),
    ("https://jannowak.com/100-szafa-metalowa-marcin-szara-socjalna", "973", "SUS 334"),
    ("https://jannowak.com/105-szafa-metalowa-karol-szara-skrytkowa", "1054", "SUS 336"),
    ("https://jannowak.com/175-szafa-metalowa-robert-szara-socjalna", "", "SUS"),
    ("https://jannowak.com/178-szafa-metalowa-oliver-szara-socjalna", "", "SUS"),
    ("https://jannowak.com/97-szafa-metalowa-bartek-szara-socjalna", "", "SUS"),
]


links = [
    ("https://jannowak.com/100-szafa-metalowa-marcin-szara-socjalna", "973", "SUS 334"),
    ("https://jannowak.com/105-szafa-metalowa-karol-szara-skrytkowa", "1054", "SUS 336"),
    ("https://jannowak.com/175-szafa-metalowa-robert-szara-socjalna", "", "SUS"),
    ("https://jannowak.com/178-szafa-metalowa-oliver-szara-socjalna", "", "SUS"),
    ("https://jannowak.com/97-szafa-metalowa-bartek-szara-socjalna", "", "SUS"),
]
