links = [
  # MEBLE SOCJALNE I BIUROWE - SZAFY UBRANIOWE
  ("https://sklep.metalkas.com.pl/szafa-metalowa-schowkowa-4mss-eco-z-czerwonymi-drwiami.html", "877", "SUS 322"),
  ("https://sklep.metalkas.com.pl/lawka-tg-lawka-600-wysuwana.html", "487", "P 321"),
  ("https://sklep.metalkas.com.pl/szafa-metalowa-tg-1msl-eco-basic.html", "846", "SUL 31"),
  ("https://sklep.metalkas.com.pl/daszek-do-szafy-3msu.html", "164", "D 420"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-z-przegroda-tg-2msu-eco-przegroda.html", "1093", "SUM 320"),
  ("https://sklep.metalkas.com.pl/tg-mss-eco-n-1800x600x490-k7035-d5017-s6-brak-wyposazenia.html", "1338", "SUM 420"),
  ("https://sklep.metalkas.com.pl/tg-5msu-eco.html", "2173", "SUM 430"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-tg-3msu-eco-mtd-1-pkt-przegrody.html", "1096", "SUM 420"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-z-przegroda-tg-2msu-eco-1-p-rygl-mtd-przegroda.html", "1027", "SUM 320"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-dwudrzwiowa-szara-tg-3msu-master.html", "1575", "SUM 420"),
  ("https://sklep.metalkas.com.pl/tg-2msu-j.html", "1403", "SUM 320"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-tg-3msu-k7035-d3020.html", "1386", "SUM 420"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-l-tg-2msl-7035.html", "2366", "SUM 420"),
  ("https://sklep.metalkas.com.pl/szafa-schowkowa-6mss-eco.html", "1432", "SUS 325"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-tg-2msu-z-niebieskimi-drzwiami.html", "986", "SUM 320"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-tg-1msu-eco-mtd-1punktowe-ryglowanie.html", "555", "SUM 310"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-tg-4msu-eco-z-niebieskimi-drzwiami.html", "1190", "SUM 330"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-tg-4msu-eco-z-czerwonymi-drzwiami.html", "1190", "SUM 330"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-tg-1msu-eco-z-niebieskimi-drzwiami.html", "517", "SUM 310"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-tg-1msu-eco-z-czerwonymi-drzwiami.html", "517", "SUM 310"),
  ("https://sklep.metalkas.com.pl/laweczka-pod-szafe-ubraniowa-tg-lawka-600.html", "388", "P 321"),
  ("https://sklep.metalkas.com.pl/szafa-metalowa-ubraniowa-tg-2msl-eco-niebieskie-drzwi.html", "1665", "SUL 42"),
  ("https://sklep.metalkas.com.pl/szafa-metalowa-ubraniowa-bhp-3msu-eco-z-niebieskimi-drzwiami.html", "1109", "SUM 420"),
  ("https://sklep.metalkas.com.pl/szafa-metalowa-ubraniowa-3-msu-eco-z-czerwonymi-drzwiami.html", "1109", "SUM 420"),
  ("https://sklep.metalkas.com.pl/szafa-bhp-ubraniowa-socjalna-tg-2msu-eco-z-czerwonymi-drzwiami.html", "789", "SUM 320"),
  ("https://sklep.metalkas.com.pl/szafa-metalowa-ubraniowa-tg-2msl-eco-czerwone-drzwi.html", "1665", "SUL 42"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-2-msu-eco-mtd-drzwi-ral1018.html", "730", "SUM 320"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-2-msu-eco-mtd-2.html", "730", "SUM 320"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-2-msu-eco-mtd-drzwi-ral5017.html", "730", "SUM 320"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-tg-msu-eco-basic.html", "645", "SUM"),
  ("https://sklep.metalkas.com.pl/lawka-szatniowa-do-szafy-ubraniowej-tg-lawka-800-pojedyncza-skladana-sal.html", "402", "P 421"),
  ("https://sklep.metalkas.com.pl/szafa-schowkowa-tg-5mss-eco.html", "1250", "SUS 324"),
  ("https://sklep.metalkas.com.pl/szafy-schowkowe-metalowe-tg-4mss-eco.html", "897", "SUS 322"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-tg-2msl-eco.html", "1892", "SUL 42"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-3-msu-1-ryglowanie.html", "1728", "SUM 420"),
  ("https://sklep.metalkas.com.pl/szafa-schowkowa-5mss-html.html", "1563", "SUS 324"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-tg-2msl-eco-basic.html", "1403", "SUL 32"),
  ("https://sklep.metalkas.com.pl/szafa-schowkowa-4mss-eco-z-niebieskimi-drzwiami.html", "877", "SUS 322"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-2-msu.html", "1120", "SUM 320"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-3-msu-eco.html", "1260", "SUM 420"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-2-msu-eco.html", "717", "SUM 320"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-3-msu-eco-mtd.html", "899", "SUM 420"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-2-msu-eco-mtd.html", "655", "SUM 320"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-6msu-met.html", "3366", "SUM 340"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-5msu-met.html", "3202", "SUM 430"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-4msu-met-m.html", "2683", "SUM 330"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-3msu-met-m.html", "2076", "SUM 420"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-3msu-met.html", "2013", "SUM 420"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-2msu-met-m.html", "1576", "SUM 320"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-2msu-met.html", "1519", "SUM 320"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-1msu-met-m.html", "1194", "SUM 310"),
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-1msu-met.html", "1164", "SUM 310"),
  # SZAFY KARTOTEKOWE
  ("https://sklep.metalkas.com.pl/szafa-kartotekowa-szufladowa-tg-2sdk-ek-grusza.html", "", "SZK"),
  ("https://sklep.metalkas.com.pl/szafa-kartotekowa-3-sdk.html", "", "SZK"),
  # BIURKA
  ("https://sklep.metalkas.com.pl/biurko-met.html", "3431", "STB 1480"),
  ("https://sklep.metalkas.com.pl/komoda-metalowa-tg-mss-k-eco.html", "", ""),
  # BIUROWE
  ("https://sklep.metalkas.com.pl/szafa-nadstawka-biurowa-tg-3nd-eco.html", "725", "SBM 403"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-tg-sdb-m60-n-1980x800x400-dodatkowy-cokol.html", "2025", "SBM 202"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-zaluzjowa-tg-4sdb-zaluzja.html", "2032", "SBM 105"),
  ("https://sklep.metalkas.com.pl/szafa-nadstawka-biurowa-tg-4nd-eco.html", "773", "SBM 405"),
  ("https://sklep.metalkas.com.pl/szafa-nadstawka-biurowa-tg-1nd-eco.html", "675", "SBM 402"),
  ("https://sklep.metalkas.com.pl/szafa-nadstawka-biurowa-tg-2nd.html", "", "SBM"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-tg-sdb-eco-basic-760.html", "1441", "SBM 202"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-tg-2sdb-1-eco.html", "1468", "SBM 201"),
  ("https://sklep.metalkas.com.pl/szafy-biurowe-tg-3sdb-pro-z-zielonymi-drzwiami.html", "2614", "SBM 203"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-sdb-eco-basic-1000.html", "1527", "SBM 203"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-tg-2sdb-1.html", "1835", "SBM 201"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-metalowa-1sdb-pro-k7035-d7024.html", "2025", "SBM"),
  ("https://sklep.metalkas.com.pl/szafa-na-dokumenty-1sdb-1-eco.html", "1391", "SBM 201"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-metalowa-tg-4sdb-eco.html", "1462", "SBM 103"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-3-sdb-met.html", "2614", "SBM 203"),
  ("https://sklep.metalkas.com.pl/szafa-metalowa-biurowa-tg-2sdb-eco-z-czerwonymi-drzwiami-1.html", "1414", "SBM 203"),
  ("https://sklep.metalkas.com.pl/szafa-metalowa-biurowa-tg-2sdb-eco-z-niebieskimi-drzwiami.html", "1414", "SBM 203"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-metalowa-tg-1sdb-eco-z-czerwonymi-drzwiami.html", "1334", "SBM 202"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-metalowa-tg-1sdb-eco-z-niebieskimi-drzwiami.html", "1334", "SBM 202"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-metalowa-tg-1sdb-eco-z-zoltymi-drzwiami.html", "1334", "SBM 202"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-metalowa-tg-4sdb.html", "1828", "SBM 103"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-metalowa-tg-1sdb-eco.html", "1516", "SBM 202"),
  ("https://sklep.metalkas.com.pl/szafa-metalowa-biurowa-tg-1sdb.html", "1895", "SBM 202"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-metalowa-tg-2sdb-eco.html", "1607", "SBM 202"),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-1-sdb-eco.html", "1738", "SBM 201"),
  ("https://sklep.metalkas.com.pl/szafa-gospodarcza-tg-msg-eco-basic-7035-1-pkt.html", "856", "MSU 62"),
  # KOLEKCJA MEBLI METROPOLITAN
  ("https://sklep.metalkas.com.pl/szafa-biurowa-tg-sdb-m60-n-1980x800x400-dodatkowy-cokol.html", "2025", "SBM 202"),
  # MEBLE LOFTOWE
  ("https://sklep.metalkas.com.pl/szafa-ubraniowa-tg-4msu-met-m-k9003-d3012-3014-3017.html", "", ""),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-metalowa-tg-1sdb-met-z-niebieskimi-drzwiami.html", "", ""),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-metalowa-tg-1sdb-met-z-czerwonymi-drzwiami.html", "", ""),
  ("https://sklep.metalkas.com.pl/szafa-biurowa-3-sdb-met-html.html", "", ""),
  ("https://sklep.metalkas.com.pl/komoda-metalowa-tg-mss-k-eco.html", "", ""),
  ("https://sklep.metalkas.com.pl/szafa-schowkowa-6mss-met.html", "2226", "SUS 325"),
  ("https://sklep.metalkas.com.pl/szafa-schowkowa-5mss-met.html", "2039", "SUS 324"),
  ("https://sklep.metalkas.com.pl/szafa-schowkowa-4mss-met-m.html", "1864", "SUS 322"),
  ("https://sklep.metalkas.com.pl/szafa-schowkowa-3mss-met.html", "1250", "SUS 314"),
  ("https://sklep.metalkas.com.pl/szafa-schowkowa-2mss-met-m.html", "1271", "SUS 313"),
  ("https://sklep.metalkas.com.pl/szafa-schowkowa-2mss-met.html", "1145", "SUS 313"),
  ("https://sklep.metalkas.com.pl/szafa-schowkowa-1mss-met-m.html", "1189", "SUS 312"),
]

links =[("https://sklep.metalkas.com.pl/szafa-schowkowa-1mss-met-m.html", "1189", "SUS 312")]

