# # Lista do analizy przekrojowej

# LINKS = [
#   ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-dwudrzwiowa/", "SUM 320W"),
#   ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-dwudrzwiowa-2/", "SUM 420W"),
#   ("https://www.kart-map.pl/produkt/szafa-skrytkowa-bhp-czterodrzwiowa/","SUS 322W"),
#   ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-czterodrzwiowa-typ-l/","SUL 42W"),
#   ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-czterodrzwiowa-typ-l-2/","SUL 32W"),
#   ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-c-2-polki-w-p1/","STW 121"),
#   ("https://www.kart-map.pl/produkt/stol-2-modulowy-1-polka-w-p2/","STW 321"),
#   ("https://www.kart-map.pl/produkt/regal-magazynowy-5-polkowy-3/","RMM 301"),
#   # ("https://www.kart-map.pl/produkt/regal-magazynowy-4/","RMM 201"),
#   # ("https://www.kart-map.pl/produkt/stolik-biurowy/","STB 1680"),
#   ("https://www.kart-map.pl/produkt/kontener-trzyszufladowy-przybiurkowy-na-kolkach/","SZP 403"),
#   ("https://www.kart-map.pl/produkt/kontener-czteroszufladowy-przybiurkowy-na-kolkach/","SZP 404"),
#   ("https://www.kart-map.pl/produkt/szafa-gospodarcza-bhp-2-drzwiowa-2/","MSU 60"),
#   ("https://www.kart-map.pl/produkt/szafa-gospodarcza-bhp-ubraniowo-polkowa/","MSU 61"),
#   ("https://www.kart-map.pl/produkt/szafa-gospodarcza-bhp-2-drzwiowa/","MSU 62"),
#   ("https://www.kart-map.pl/produkt/szafa-gospodarcza-bhp-ubraniowo-polkowa-2/","MSU 81"),
# ]

LINKS = [
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-dwudrzwiowa/", "SUM 320W"),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-dwudrzwiowa-2/", "SUM 420W"),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-bhp-czterodrzwiowa/", "SUS 322W"),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-czterodrzwiowa-typ-l/", "SUL 42W"),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-czterodrzwiowa-typ-l-2/", "SUL 32W"),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-c-2-polki-w-p1/", "STW 121"),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-1-polka-w-p2/", "STW 321"),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-5-polkowy-3/", "RMM 301"),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-4/", "RMM 201"),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-czteropolkowa-z-drzwiami-uchylnymi-idealna-do-przechowywania-dokumentow-rodo-2018/", "SBM 203"),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-czteropolkowa-z-drzwiami-zaluzjowymi/", "SBM 208"),
  ("https://www.kart-map.pl/produkt/szafa-do-kartotek-for-a-4-cztery-szuflady/", "SZK 301"),
  ("https://www.kart-map.pl/produkt/szafa-do-segregatorow-i-teczek-wiszacych-for-a-4-4-szuflady2-rzedy/", "SZK 302"),
  ("https://www.kart-map.pl/produkt/szafa-do-kartotek-for-a-5-piec-szuflad/", "SZK 304"),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-piec-szuflad/", "SZK 318"),
  ("https://www.kart-map.pl/produkt/szafa-do-kartotek-for-a-6-piec-szuflad/", "SZK 203"),
  ("https://www.kart-map.pl/produkt/szafa-do-segregatorow-i-teczek-wiszacych-for-a-3-3-szuflady/", "SZK A3"),
  ("https://www.kart-map.pl/produkt/szafa-na-plany-i-mapy-for-a-0-piec-szuflad/", "SRM 100"),
  ("https://www.kart-map.pl/produkt/szafa-na-plany-i-mapy-for-a-1-piec-szuflad/", "SRM 101"),
  ("https://www.kart-map.pl/produkt/stolik-biurowy/", "STB 1680"),
  ("https://www.kart-map.pl/produkt/kontener-trzyszufladowy-przybiurkowy-na-kolkach/", "SZP 520"),
  ("https://www.kart-map.pl/produkt/kontener-czteroszufladowy-przybiurkowy-na-kolkach/", "SZP 530"),
  ("https://www.kart-map.pl/produkt/szafa-1-drzwiowa-przeszklone-drzwi/", "SML 101"),
  ("https://www.kart-map.pl/produkt/szafa-dwudzielna-przeszklone-gorne-drzwi-2/", "SML 114"),
  ("https://www.kart-map.pl/produkt/szafa-wiszaca-2-drzwiowa-przeszklone-drzwi-przesuwne/", "SZL 103"),
  ("https://www.kart-map.pl/produkt/szafa-gospodarcza-bhp-2-drzwiowa-2/", "MSU 60"),
  ("https://www.kart-map.pl/produkt/szafa-gospodarcza-bhp-ubraniowo-polkowa/", "MSU 61"),
  ("https://www.kart-map.pl/produkt/szafa-gospodarcza-bhp-2-drzwiowa/", "MSU 62"),
  ("https://www.kart-map.pl/produkt/szafa-gospodarcza-bhp-ubraniowo-polkowa-2/", "MSU 81"),
]