links = [
# Biurowe
    ("https://jannowak.com/29-szafa-metalowa-alex-szara-aktowa", "", ""),
    ("https://jannowak.com/66-szafa-metalowa-kevin-szara", "", ""),
    ("https://jannowak.com/1-szafa-metalowa-jan-szara", "", ""),
    ("https://jannowak.com/20-szafa-metalowa-jan-ii-szara", "", ""),
    ("https://jannowak.com/8-szafa-metalowa-jan-h-szara", "", ""),
    ("https://jannowak.com/85-szafa-metalowa-wiola-szara-aktowa", "", ""),
    ("https://jannowak.com/116-szafa-metalowa-edmund-szara", "", ""),
    ("https://jannowak.com/89-szafa-metalowa-szara-medyczna", "", ""),
    ("https://jannowak.com/180-szafa-metalowa-nadstawka-ewa-szara", "", ""),
    ("https://jannowak.com/45-szafa-metalowa-beata-szara", "", ""),
    ("https://jannowak.com/39-szafa-metalowa-damian-szara", "", ""),
    ("https://jannowak.com/54-szafa-metalowa-kuba-szara", "", ""),
    ("https://jannowak.com/53-szafa-metalowa-magda-szara", "", ""),
    ("https://jannowak.com/94-szafa-metalowa-borys-szara", "", ""),
    ("https://jannowak.com/127-szafa-metalowa-sara-szara-kartotekowa", "", ""),
    ("https://jannowak.com/134-szafa-metalowa-sara-szara-kartotekowa", "", ""),
    ("https://jannowak.com/174-szafa-metalowa-dawid-szara-socjalna", "", ""),
    ("https://jannowak.com/178-szafa-metalowa-oliver-szara-socjalna", "", ""),
    ("https://jannowak.com/215-zestaw-jan-ewa-szary", "", ""),
    ("https://jannowak.com/131-szafa-metalowa-sara-szara-kartotekowa", "", ""),
    ("https://jannowak.com/77-szafa-metalowa-filip-szara-z-sejfem", "", ""),
    ("https://jannowak.com/23-szafa-metalowa-daniel-szara-zamek-elektroniczny", "", ""),
    ("https://jannowak.com/59-szafa-metalowa-tomasz-szara-ze-schowkiem", "", ""),
    ("https://jannowak.com/80-szafa-metalowa-filip-ii-szara-z-sejfem", "", ""),
    ("https://jannowak.com/179-szafa-metalowa-lena-szara", "", ""),
    ("https://jannowak.com/184-szafa-metalowa-regal-maks-szara", "", ""),
    ("https://jannowak.com/168-szafa-metalowa-adam-szara-socjalna", "", ""),
    ("https://jannowak.com/119-szafa-metalowa-kacper-ii-szara-socjalna", "", ""),
    ("https://jannowak.com/120-szafa-metalowa-kacper-szara-socjalna", "", ""),
    ("https://jannowak.com/176-szafa-metalowa-socjalna-julia-szara", "", ""),
    ("https://jannowak.com/111-szafa-metalowa-igor-szara", "", ""),
    ("https://jannowak.com/100-szafa-metalowa-marcin-szara-socjalna", "", ""),
    ("https://jannowak.com/105-szafa-metalowa-karol-szara-skrytkowa", "", ""),
    ("https://jannowak.com/175-szafa-metalowa-robert-szara-socjalna", "", ""),
    ("https://jannowak.com/178-szafa-metalowa-oliver-szara-socjalna", "", ""),
    ("https://jannowak.com/97-szafa-metalowa-bartek-szara-socjalna", "", ""),
]

links = [
    ("https://jannowak.com/97-szafa-metalowa-bartek-szara-socjalna", "", ""),
    ("https://jannowak.com/105-szafa-metalowa-karol-szara-skrytkowa", "", ""),
]