'''
1. Sprawdzić linki, poprzednia cene wpisac do pierwszego miejsca po linku
2. w drugie miejsce wpisac odpowiednik Malowa

'''

links = [
  # Szafy BHP – ubraniowe 
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-dwudrzwiowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-dwudrzwiowa-z-lawka/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-dwudrzwiowa-z-perforacja-i-lawka/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-dwudrzwiowa-z-perforacja-na-nozkach/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-trzydrzwiowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-dwudrzwiowa-2/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-dwudrzwiowa-z-lawka-2/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-jednodrzwiowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-jednodrzwiowa-z-lawka/", "", ""),
  # Szafy skrytkowe
  ("https://www.kart-map.pl/produkt/szafa-depozytowa-30-drzwiowa-szesciokolumnowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-bhp-czterodrzwiowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-bhp-szesciodrzwiowa-trzykolumnowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-bhp-szesciodrzwiowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-bhp-osmiodrzwiowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-bhp-dziesieciodrzwiowa/", "", ""),
  # Szafy BHP typu L
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-dwudrzwiowa-typ-l/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-czterodrzwiowa-typ-l/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-dwudrzwiowa-z-lawka-typ-l/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-czterodrzwiowa-z-lawka-typ-l/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-czterodrzwiowa-z-perforacja-typ-l/", "", ""),
  # Szafy gospodarcze BHP
  ("https://www.kart-map.pl/produkt/szafa-gospodarcza-bhp-ubraniowo-polkowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-gospodarcza-bhp-2-drzwiowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-gospodarcza-bhp-2-drzwiowa-2/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-gospodarcza-bhp-ubraniowo-polkowa-2/", "", ""),
  # Daszki do szaf
  ("https://www.kart-map.pl/produkt/daszek-do-szafy/", "", ""),
  ("https://www.kart-map.pl/produkt/daszek-do-szafy-2/", "", ""),
  ("https://www.kart-map.pl/produkt/daszek-do-szafy-kopia/", "", ""),
  ("https://www.kart-map.pl/produkt/daszek-do-szafy-3/", "", ""),
  ("https://www.kart-map.pl/produkt/daszek-do-szafy-4/", "", ""),
  # Ławki stałe
  ("https://www.kart-map.pl/produkt/lawka-podstawa-pod-szafe/", "", ""),
  ("https://www.kart-map.pl/produkt/lawka-podstawa-pod-szafe-2/", "", ""),
  ("https://www.kart-map.pl/produkt/lawka-podstawa-pod-szafe-3/", "", ""),
  ("https://www.kart-map.pl/produkt/lawka-podstawa-pod-szafe-4/", "", ""),
  ("https://www.kart-map.pl/produkt/lawka-podstawa-pod-szafe-5/", "", ""),
  # Ławki Wysuwane
  ("https://www.kart-map.pl/produkt/lawka-wysuwana-podstawa-pod-szafe/", "", ""),
  ("https://www.kart-map.pl/produkt/lawka-wysuwana-podstawa-pod-szafe-2/", "", ""),
  ("https://www.kart-map.pl/produkt/lawka-wysuwana-podstawa-pod-szafe-3/", "", ""),
  ("https://www.kart-map.pl/produkt/lawka-wysuwana-podstawa-pod-szafe-4/", "", ""),
  ("https://www.kart-map.pl/produkt/lawka-wysuwana-podstawa-pod-szafe-5/", "", ""),
  # Półki na buty
  ("https://www.kart-map.pl/produkt/polka-na-buty-do-szafy/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-na-buty-do-szafy-2/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-na-buty-do-szafy-3/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-na-buty-do-szafy-4/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-na-buty-do-szafy-5/", "", ""),
  # Nóżki do szaf
  ("https://www.kart-map.pl/produkt/nozki-z-blachy/", "", ""),
  ("https://www.kart-map.pl/produkt/nozki-z-blachy-ze-stopkami-regulowanymi/", "", ""),
  # Ławki szatniowe wolnostojące
  ("https://www.kart-map.pl/produkt/lawka-szatniowa-wolnostojaca-5/", "", ""),
  ("https://www.kart-map.pl/produkt/lawka-szatniowa-wolnostojaca-3/", "", ""),
  ("https://www.kart-map.pl/produkt/lawka-szatniowa-wolnostojaca-4/", "", ""),
  ("https://www.kart-map.pl/produkt/lawka-szatniowa-wolnostojaca/", "", ""),
  ("https://www.kart-map.pl/produkt/lawka-szatniowa-wolnostojaca-2/", "", ""),
  # Szafy biurowe z drzwiami uchylnymi
  ("https://www.kart-map.pl/produkt/szafa-biurowa-czteropolkowa-z-drzwiami-uchylnymi-idealna-do-przechowywania-dokumentow-rodo-2018-2/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-trzypolkowa-ze-skrytka-idealna-do-przechowywania-dokumentow-rodo-2018/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-jednoskrzydlowa-czteropolkowa-idealna-do-przechowywania-dokumentow-rodo-2018/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-dwupolkowa-z-drzwiami-uchylnymi-idealna-do-przechowywania-dokumentow-rodo-2018-2/", "", ""),
  ("https://www.kart-map.pl/produkt/nadstawka-do-szafy-biurowej-z-drzwiami-uchylnymi-idealna-do-przechowywania-dokumentow-rodo-2018/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-czteropolkowa-z-drzwiami-uchylnymi-idealna-do-przechowywania-dokumentow-rodo-2018/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-trzypolkowa-ze-skrytka-idealna-do-przechowywania-dokumentow-rodo-2018-2/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-dwupolkowa-z-drzwiami-uchylnymi-idealna-do-przechowywania-dokumentow-rodo-2018/", "", ""),
  ("https://www.kart-map.pl/produkt/nadstawka-do-szafy-biurowej-z-drzwiami-uchylnymi-idealna-do-przechowywania-dokumentow-rodo-2018-2/", "", ""),
  # Szafy biurowe z drzwiami przesuwnymi
  ("https://www.kart-map.pl/produkt/szafa-biurowa-czteropolkowa-z-drzwiami-przesuwnymi-idealna-do-przechowywania-dokumentow-rodo-2018/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-dwupolkowa-z-drzwiami-przesuwnymi-idealna-do-przechowywania-dokumentow-rodo-2018/", "", ""),
  ("https://www.kart-map.pl/produkt/nadstawka-do-szafy-biurowej-z-drzwiami-przesuwnymi-idealna-do-przechowywania-dokumentow-rodo-2018/", "", ""),
  # Szafy biurowe z drzwiami żaluzjowymi
  ("https://www.kart-map.pl/produkt/szafa-biurowa-czteropolkowa-z-drzwiami-zaluzjowymi/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-dwupolkowa-z-drzwiami-zaluzjowymi/", "", ""),
  ("https://www.kart-map.pl/produkt/nadstawka-do-szafy-biurowej-z-drzwiami-zaluzjowymi/", "", ""),
  # Szafy biurowe na dokumenty niejawne
  ("https://www.kart-map.pl/produkt/wzmocniona-szafa-3-polkowa-2-drzwiowa-ze-skrytka-idealna-do-przechowywania-dokumentow-rodo/", "", ""),
  ("https://www.kart-map.pl/produkt/wzmocniona-szafa-4-polkowa-2-drzwiowa-idealna-do-przechowywania-dokumentow-rodo-2018/", "", ""),
  ("https://www.kart-map.pl/produkt/wzmocniona-szafa-2-polkowa-2-drzwiowa-idealna-do-przechowywania-dokumentow-rodo-2018/", "", ""),
  ("https://www.kart-map.pl/produkt/wzmocniona-szafa-2-drzwiowa-idealna-do-przechowywania-dokumentow-rodo-2018/", "", ""),
  ("https://www.kart-map.pl/produkt/wzmocniona-szafa-4-polkowa-1-drzwiowa-idealna-do-przechowywania-dokumentow-rodo/", "", ""),
  ("https://www.kart-map.pl/produkt/wzmocniona-szafa-3-polkowa-1-drzwiowa-idealna-do-przechowywania-dokumentow-rodo-2018/", "", ""),
  ("https://www.kart-map.pl/produkt/wzmocniona-szafa-1-polkowa-1-drzwiowa-idealna-do-przechowywania-dokumentow-rodo-2018/", "", ""),
  # Szafy biurowe witrynowe
  ("https://www.kart-map.pl/produkt/szafa-biurowa-witrynowa-czteropolkowa-z-drzwiami-uchylnymi-idealna-do-przechowywania-dokumentow-rodo-kopia/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-witrynowa-czteropolkowa-z-drzwiami-uchylnymi-idealna-do-przechowywania-dokumentow-rodo/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-witrynowa-dwudzielna-z-drzwiami-uchylnymi-idealna-do-przechowywania-dokumentow-rodo/", "", ""),
  # Kontenery przybiurkowe
  ("https://www.kart-map.pl/produkt/kontener-trzyszufladowy-przybiurkowy-na-kolkach/", "", ""),
  ("https://www.kart-map.pl/produkt/kontener-czteroszufladowy-przybiurkowy-na-kolkach/", "", ""),
  # Stoły biurowe
  ("https://www.kart-map.pl/produkt/stolik-biurowy/", "", ""),
  ("https://www.kart-map.pl/produkt/biurko-z-oslona-tylna/", "", ""),
  ("https://www.kart-map.pl/produkt/biurko-z-oslona-tylna-oraz-podstawa/", "", ""),
  ("https://www.kart-map.pl/produkt/biurko-z-oslona-tylna-oraz-kontenerem/", "", ""),
  # Szafy medyczne
  ("https://www.kart-map.pl/produkt/szafa-1-drzwiowa-przeszklone-drzwi/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-1-drzwiowa-przeszklone-drzwi-i-boki/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-dwudzielna-przeszklone-gorne-drzwi/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-dwudzielna-przeszklone-gorne-drzwi-i-boki/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-2-drzwiowa-przeszklone-drzwi/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-2-drzwiowa-przeszklone-drzwi-i-boki/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-dwudzielna-przeszklone-gorne-drzwi-2/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-dwudzielna-przeszklone-gorne-drzwi-i-boki-2/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-wiszaca-1-drzwiowa-przeszklone-drzwi/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-wiszaca-2-drzwiowa-przeszklone-drzwi/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-wiszaca-2-drzwiowa-przeszklone-drzwi-przesuwne/", "", ""),
  # Szafy kartotekowe na dokumenty medyczne
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-dwie-szuflady-kop-2s/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-trzy-szuflady/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-cztery-szuflady/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-piec-szuflad/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-szesc-szuflad/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-siedem-szuflad/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-dwie-szuflady-1-rzedowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-trzy-szuflady-1-rzedowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-cztery-szuflady-1-rzedowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-piec-szuflad-1-rzedowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-szesc-szuflad-1-rzedowa-2/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-szesc-szuflad-1-rzedowa/", "", ""),
  # Akcesoria do szaf medycznych
  ("https://www.kart-map.pl/produkt/nozki-z-blachy/", "", ""),
  ("https://www.kart-map.pl/produkt/nozki-z-blachy-ze-stopkami-regulowanymi/", "", ""),
  ("https://www.kart-map.pl/produkt/kola-2-stale-2-skretne-w-tym-jedno-z-hamulcem/", "", ""),
  # Meble na stacje paliw
  ("https://www.kart-map.pl/produkt/szafa-zaluzjowa-na-kolkach/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-zaluzjowa-na-kolkach-2/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-zaluzjowa-na-stopkach/", "", ""),
  ("https://www.kart-map.pl/produkt/uchylna-na-stopkach-2/", "", ""),
  # Szafy ubraniowe szkolne i przedszkolne
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-szkolna/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-szkolna-2/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-przedszkolna/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-szkolna-3/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-szkolna-4/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-przedszkolna-2/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-szkolna-5/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-szkolna-6/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-przedszkolna-3/", "", ""),
  # Szafy ubraniowe szkolne i przedszkolne
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-szkolna/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-szkolna-2/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-przedszkolna/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-szkolna-3/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-szkolna-kopia/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-przedszkolna-2/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-szkolna-4/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-szkolna-5/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-przedszkolna-3/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-szkolna-6/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-szkolna-7/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-przedszkolna-4/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-szkolna-8/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-szkolna-10/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-szkolna-9/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-szkolna-11/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-szkolna-12/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-przedszkolna-5/", "", ""),
  # Kosze do segregacji odpadów
  ("https://www.kart-map.pl/produkt/jednokomorowy-kosz-zewnetrzny-do-segregowania-odpadow/", "", ""),
  ("https://www.kart-map.pl/produkt/dwukomorowy-kosz-zewnetrzny-do-segregowania-odpadow/", "", ""),
  ("https://www.kart-map.pl/produkt/trzykomorowy-kosz-zewnetrzny-do-segregowania-odpadow/", "", ""),
  ("https://www.kart-map.pl/produkt/czterokomorowy-kosz-zewnetrzny-do-segregowania-odpadow/", "", ""),
  # Nadstawki do stołów warsztatowych 2-modułowych seria W-2N
  ("https://www.kart-map.pl/produkt/nadstawka-1-rzedowa-z-dwoma-panelami-perforowanymi/", "", ""),
  ("https://www.kart-map.pl/produkt/nadstawka-2-rzedowa-z-czterema-panelami-perforowanymi/", "", ""),
  ("https://www.kart-map.pl/produkt/nadstawka-2-rzedowa-z-trzema-panelami-perforowanymi-i-szafka/", "", ""),
  ("https://www.kart-map.pl/produkt/nadstawka-2-rzedowa-z-dwoma-panelami-perforowanymi-i-dwiema-szafkami/", "", ""),
  ("https://www.kart-map.pl/produkt/nadstawka-2-rzedowa-z-dwoma-panelami-perforowanymi-i-uchwytami-na-poj/", "", ""),
  # Nadstawki do stołów warsztatowych 3 – modułowych seria W-3N
  ("https://www.kart-map.pl/produkt/nadstawka-1-rzedowa-z-trzema-panelami-perforowanymi/", "", ""),
  ("https://www.kart-map.pl/produkt/nadstawka-2-rzedowa-z-szescioma-panelami-perforowanymi/", "", ""),
  ("https://www.kart-map.pl/produkt/nadstawka-2-rzedowa-z-piecioma-panelami-perforowanymi-i-szafka/", "", ""),
  ("https://www.kart-map.pl/produkt/nadstawka-2-rzedowa-z-czterema-panelami-perforowanymi-i-dwiema-szafkami/", "", ""),
  ("https://www.kart-map.pl/produkt/nadstawka-2-rzedowa-z-trzema-panelami-perforowanymi-i-trzema-szafkami/", "", ""),
  ("https://www.kart-map.pl/produkt/nadstawka-2-rzedowa-z-trzema-panelami-perforowanymi-i-uchwytami-na-poj/", "", ""),
  # Akcesoria do nadstawek do stołów warsztatowych
  ("https://www.kart-map.pl/produkt/szafka-1-drzwiowa/", "", ""),
  ("https://www.kart-map.pl/produkt/panel-perforowany-1-segmentowy/", "", ""),
  ("https://www.kart-map.pl/produkt/haczyk-pojedynczy/", "", ""),
  ("https://www.kart-map.pl/produkt/haczyk-pojedynczy-2/", "", ""),
  ("https://www.kart-map.pl/produkt/haczyk-pojedynczy-3/", "", ""),
  ("https://www.kart-map.pl/produkt/haczyk-podwojny/", "", ""),
  ("https://www.kart-map.pl/produkt/haczyk-podwojny-2/", "", ""),
  ("https://www.kart-map.pl/produkt/mocowanie-pojemnikow-plastikowych-malych/", "", ""),
  ("https://www.kart-map.pl/produkt/mocowanie-pojemnikow-plastikowych-duzych/", "", ""),
  ("https://www.kart-map.pl/produkt/pojemnik-metalowy/", "", ""),
  ("https://www.kart-map.pl/produkt/pojemnik-metalowy-kopia/", "", ""),
  ("https://www.kart-map.pl/produkt/pojemnik-metalowy-2/", "", ""),
  ("https://www.kart-map.pl/produkt/uchwyt-na-klucze-plaskie/", "", ""),
  ("https://www.kart-map.pl/produkt/uchwyt-na-wkretaki/", "", ""),
  ("https://www.kart-map.pl/produkt/uchwyt-na-spray-maly/", "", ""),
  ("https://www.kart-map.pl/produkt/uchwyt-na-spray-duzy/", "", ""),
  ("https://www.kart-map.pl/produkt/uchwyt-na-wiertla/", "", ""),
  ("https://www.kart-map.pl/produkt/uchwyt-na-kombinerki/", "", ""),
  ("https://www.kart-map.pl/produkt/mocowanie-paneli-niskie-2-segmentowe/", "", ""),
  ("https://www.kart-map.pl/produkt/mocowanie-paneli-niskie-3-segmentowe/", "", ""),
  ("https://www.kart-map.pl/produkt/mocowanie-paneli-wysokie-2-segmentowe/", "", ""),
  ("https://www.kart-map.pl/produkt/mocowanie-paneli-wysokie-3-segmentowe/", "", ""),
  # Stoły warsztatowe 2-modułowe seria WD2
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-baza-bez-dodatkowego-wyposazenia/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-1-polka-w-p2/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-2-polki-w-p2/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-a/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-b-1-polka-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-c-2-polki-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-a-szafka-wsz-b/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-b-szafka-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-c-szafka-wsz-d/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-a-polka-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-a-2-polki-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-2x-szafki-wsz-a/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-a-szafka-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-a-szafka-wsz-d/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-b/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-b-2-polki-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-b-szafka-wsz-b/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-b-szafka-wsz-d/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-c-polka-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-c-szafka-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-d/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-d-polka-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowe-szafka-wsz-d-2-polki-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-d-szafka-wsz-d/", "", ""),
  # Stoły warsztatowe 3-modułowe seria WD3
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-baza-bez-dodatkowego-wyposazenia/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-polka-w-p3/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-polki-w-p3/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-a/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-b-polka-w-p2/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-c-2-polki-w-p2/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-a-szafka-wsz-b/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-b-szafa-wsz-c-polka-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-c-szafka-wsz-d-2-polki-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-c-szafka-wsz-b-szafka-wsz-a/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-d-szafka-wsz-c-szafka-wsz-a/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-d-szafka-wsz-c-szafka-wsz-b/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-a-polka-w-p2/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-a-2-polki-w-p2/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-a/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-a-polka-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-a-2-polki-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-3-szafki-wsz-a/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-a-szafka-wsz-b/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-a-szafka-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-a-szafka-wsz-d/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-a-szafka-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-a-szafka-wsz-d/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-a-szafka-wsz-b-polka-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-a-szafka-wsz-b-2-polki-w-p1kopia/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-a-szafka-wsz-c-polka-w-p11kopia-kopia/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-a-szafka-wsz-c-polka-w-p11kopia-kopia-kopia/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-a-szafka-wsz-d-polka-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-a-szafka-wsz-d-2-polki-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-a-szafka-wsz-d-szafka-wsz-b/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-b/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-b-2-polki-w-p2/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-b/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-b-polka-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-b-2-polki-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-3-szafki-wsz-b/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-b-szafka-wsz-a/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-b-szafka-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-b-szafka-wsz-d/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-b-szafka-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-b-szafka-wsz-d/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-b-szafka-wsz-c-2-polki-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-b-szafka-wsz-d-polka-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-b-szafka-wsz-d-2-polki-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-c-polka-w-p2/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-c-polka-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-c-2-polki-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-3-szafki-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-a-2-szafki-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-b-2-szafki-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-d-2-szafki-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-d-szafka-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-d-szafka-wsz-c-polke-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-d/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-d-polka-w-p2/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-d-2-polki-w-p2/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-d/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-d-polka-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-d-2-polki-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-3-szafki-wsz-d/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-d-szafka-wsz-a/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-d-2-polki-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-3-szafki-wsz-d/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-d-szafka-wsz-a/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-d-szafka-wsz-b/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-2-szafki-wsz-d-szafka-wsz-c/", "", ""),
  # Akcesoria do stołów warsztatowych
  ("https://www.kart-map.pl/produkt/komplet-przegrod-do-szuflady-stolu-warsztatowego-w-prz/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-warsztatowa-w-p1/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-warsztatowa-w-p2/", "", ""),
  ("https://www.kart-map.pl/produkt/nakladka-gumowa-na-blat-stolu-warsztatowego-2-modulowego-w-gb2/", "", ""),
  ("https://www.kart-map.pl/produkt/nakladka-gumowa-na-blat-stolu-warsztatowego-3-modulowego-w-gb3/", "", ""),
  ("https://www.kart-map.pl/produkt/nakladka-z-blachy-ocynkowanej-na-blat-stolu-warsztatowego-2-modulowego-w-mb2-15/", "", ""),
  ("https://www.kart-map.pl/produkt/nakladka-z-blachy-ocynkowanej-na-blat-stolu-warsztatowego-3-modulowego-w-mb3-15/", "", ""),
  ("https://www.kart-map.pl/produkt/oswietlenie-do-stolu-warsztatowego-2-modulowego-w-os2/", "", ""),
  ("https://www.kart-map.pl/produkt/oswietlenie-do-stolu-warsztatowego-3-modulowego-w-os3/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-warsztatowa-w-p3/", "", ""),
  ("https://www.kart-map.pl/produkt/wkladka-gumowa-do-szuflady-stolu-warsztatowego-w-gsz/", "", ""),
  ("https://www.kart-map.pl/produkt/stopki-poziomujace-w-st/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-1-drzwi-1-szuflada-wsz-b/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-1-drzwiowa-wsz-a/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-3-szufladowa-wsz-c/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-4-szufladowa-wsz-d/", "", ""),
  # Wózki warsztatowe małe seria WZ
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-5-szuflad-1-szafka/", "", ""),
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-4-szuflady-1-szafka/", "", ""),
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-2-szuflady-2-szafki/", "", ""),
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-2-szafki/", "", ""),
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-8-szuflad/", "", ""),
  # Wózki warsztatowe duże seria WZ
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-5-szuflad-1-szafka-2/", "", ""),
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-4-szuflady-1-szafka-2/", "", ""),
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-2-szuflady-2-szafki-2/", "", ""),
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-2-szafki-2/", "", ""),
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-10-szuflad/", "", ""),
  # Wózki warsztatowe duże seria WZ
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-4-szufladowy/", "", ""),
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-5-szufladowy/", "", ""),
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-6-szufladowy/", "", ""),
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-7-szufladowy/", "", ""),
  # Regały magazynowe skręcane
  ("https://www.kart-map.pl/produkt/regal-magazynowy/", "", ""),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-2/", "", ""),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-3/", "", ""),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-4/", "", ""),
  ("https://www.kart-map.pl/produkt/ogranicznik-boczny-do-regalu-rm-3/", "", ""),
  ("https://www.kart-map.pl/produkt/ogranicznik-boczny-do-regalu-rm-4/", "", ""),
  ("https://www.kart-map.pl/produkt/ogranicznik-boczny-do-regalu-rm-5/", "", ""),
  ("https://www.kart-map.pl/produkt/ogranicznik-boczny-do-regalu-rm-6/", "", ""),
  ("https://www.kart-map.pl/produkt/ogranicznik-tylny-do-regalu/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-do-regalu-rm-3-dodatkowa/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-do-regalu-rm-4-dodatkowa/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-do-regalu-rm-5-dodatkowa/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-do-regalu-rm-6-dodatkowa/", "", ""),
  # Regały magazynowe zaczepowe
  ("https://www.kart-map.pl/produkt/regal-magazynowy-5-polkowy/", "", ""),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-5-polkowy-2/", "", ""),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-5-polkowy-3/", "", ""),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-5-polkowy-4/", "", ""),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-4-polkowy/", "", ""),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-4-polkowy-2/", "", ""),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-4-polkowy-3/", "", ""),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-4-polkowy-kopia/", "", ""),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-4-polkowy-4/", "", ""),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-3-polkowy/", "", ""),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-3-polkowy-2/", "", ""),
  ("https://www.kart-map.pl/produkt/regal-magazynowy-3-polkowy-3/", "", ""),
  ("https://www.kart-map.pl/produkt/lacznik-regalow-komplet-4-szt/", "", ""),
  ("https://www.kart-map.pl/produkt/ogranicznik-boczny-300/", "", ""),
  ("https://www.kart-map.pl/produkt/ogranicznik-boczny-400/", "", ""),
  ("https://www.kart-map.pl/produkt/ogranicznik-boczny-500/", "", ""),
  ("https://www.kart-map.pl/produkt/ogranicznik-boczny-600/", "", ""),
  ("https://www.kart-map.pl/produkt/ogranicznik-tylny/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-ze-wspornikami/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-ze-wspornikami-2/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-ze-wspornikami-3/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-ze-wspornikami-4/", "", ""),
  # Szafy kartotekowe na dokumenty form. A4
  ("https://www.kart-map.pl/produkt/szafa-do-kartotek-for-a-4-dwie-szuflady/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kartotek-for-a-4-trzy-szuflady/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kartotek-for-a-4-cztery-szuflady/", "", ""),
  # Szafy kartotekowe na dokumenty form. A5
  ("https://www.kart-map.pl/produkt/szafa-do-kartotek-for-a-5-dwie-szuflady/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kartotek-for-a-5-trzy-szuflady/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kartotek-for-a-5-cztery-szuflady/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kartotek-for-a-5-piec-szuflad/", "", ""),
  # Szafy kartotekowe na dokumenty form. A6
  ("https://www.kart-map.pl/produkt/szafa-do-kartotek-for-a-6-piec-szuflad/", "", ""),
  # Szafy kartotekowe na koperty form. B5 (dokumenty medyczne)
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-dwie-szuflady-kop-2s/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-trzy-szuflady/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-cztery-szuflady/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-piec-szuflad/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-szesc-szuflad/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-siedem-szuflad/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-dwie-szuflady-1-rzedowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-trzy-szuflady-1-rzedowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-cztery-szuflady-1-rzedowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-piec-szuflad-1-rzedowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-szesc-szuflad-1-rzedowa-2/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-szesc-szuflad-1-rzedowa/", "", ""),
  # Szafy kartotekowe na teczki wiszące
  ("https://www.kart-map.pl/produkt/szafa-do-segregatorow-i-teczek-wiszacych-for-a-4-2-szuflady/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-segregatorow-i-teczek-wiszacych-for-a-4-3-szuflady/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-segregatorow-i-teczek-wiszacych-for-a-4-4-szuflady/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-segregatorow-i-teczek-wiszacych-for-a-4-4-szuflady2-rzedy/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-segregatorow-i-teczek-wiszacych-for-a-3-3-szuflady/", "", ""),
  # Szafy na plany i mapy na format A0
  ("https://www.kart-map.pl/produkt/szafa-na-plany-i-mapy-for-a-0-piec-szuflad/", "", ""),
  # Szafy na plany i mapy na format A1
  ("https://www.kart-map.pl/produkt/szafa-na-plany-i-mapy-for-a-1-piec-szuflad/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-na-plany-i-mapy-for-a-1-dziesiec-szuflad/", "", ""),
  # Szafy na plany i mapy na format B1
  ("https://www.kart-map.pl/produkt/szafa-na-montaze-for-b-1-piec-szuflad/", "", ""),
  # Szafy na plany i mapy z podświetlanym blatem
  ("https://www.kart-map.pl/produkt/szafa-na-plany-i-mapy-for-a-1-podswietlany-blat-7-szuflad/", "", ""),
  # Stoły montażowe
  ("https://www.kart-map.pl/produkt/stol-montazowy-sztywny-for-a-0/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-montazowy-sztywny-for-a-1/", "", ""),
]

links = [
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-dwudrzwiowa-z-perforacja-na-nozkach/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-bhp-szesciodrzwiowa-trzykolumnowa/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-bhp-dwudrzwiowa-z-lawka-typ-l/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-gospodarcza-bhp-2-drzwiowa-2/", "", ""),
  ("https://www.kart-map.pl/produkt/daszek-do-szafy-kopia/", "", ""),
  ("https://www.kart-map.pl/produkt/lawka-podstawa-pod-szafe-4/", "", ""),
  ("https://www.kart-map.pl/produkt/lawka-wysuwana-podstawa-pod-szafe-3/", "", ""),
  ("https://www.kart-map.pl/produkt/polka-na-buty-do-szafy-3/", "", ""),
  ("https://www.kart-map.pl/produkt/nozki-z-blachy-ze-stopkami-regulowanymi/", "", ""),
  ("https://www.kart-map.pl/produkt/lawka-szatniowa-wolnostojaca-4/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-jednoskrzydlowa-czteropolkowa-idealna-do-przechowywania-dokumentow-rodo-2018/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-dwupolkowa-z-drzwiami-przesuwnymi-idealna-do-przechowywania-dokumentow-rodo-2018/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-dwupolkowa-z-drzwiami-zaluzjowymi/", "", ""),
  ("https://www.kart-map.pl/produkt/wzmocniona-szafa-4-polkowa-1-drzwiowa-idealna-do-przechowywania-dokumentow-rodo/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-biurowa-witrynowa-czteropolkowa-z-drzwiami-uchylnymi-idealna-do-przechowywania-dokumentow-rodo-kopia/", "", ""),
  ("https://www.kart-map.pl/produkt/kontener-czteroszufladowy-przybiurkowy-na-kolkach/", "", ""),
  ("https://www.kart-map.pl/produkt/biurko-z-oslona-tylna-oraz-kontenerem/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-dwudzielna-przeszklone-gorne-drzwi-i-boki/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-piec-szuflad/", "", ""),
  ("https://www.kart-map.pl/produkt/kola-2-stale-2-skretne-w-tym-jedno-z-hamulcem/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-zaluzjowa-na-stopkach/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-ubraniowa-szkolna-5/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-skrytkowa-szkolna-3/", "", ""),
  ("https://www.kart-map.pl/produkt/trzykomorowy-kosz-zewnetrzny-do-segregowania-odpadow/", "", ""),
  ("https://www.kart-map.pl/produkt/nadstawka-2-rzedowa-z-dwoma-panelami-perforowanymi-i-dwiema-szafkami/", "", ""),
  ("https://www.kart-map.pl/produkt/nadstawka-2-rzedowa-z-czterema-panelami-perforowanymi-i-dwiema-szafkami/", "", ""),
  ("https://www.kart-map.pl/produkt/haczyk-pojedynczy-2/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-2-modulowy-szafka-wsz-a-szafka-wsz-b/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-3-modulowy-szafka-wsz-d-2-polki-w-p2/", "", ""),
  ("https://www.kart-map.pl/produkt/wkladka-gumowa-do-szuflady-stolu-warsztatowego-w-gsz/", "", ""),
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-4-szuflady-1-szafka/", "", ""),
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-4-szuflady-1-szafka-2/", "", ""),
  ("https://www.kart-map.pl/produkt/wozek-warsztatowy-6-szufladowy/", "", ""),
  ("https://www.kart-map.pl/produkt/ogranicznik-boczny-do-regalu-rm-4/", "", ""),
  ("https://www.kart-map.pl/produkt/ogranicznik-boczny-500/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kartotek-for-a-4-trzy-szuflady/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kartotek-for-a-5-trzy-szuflady/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-kopert-formatu-b-5-siedem-szuflad/", "", ""),
  ("https://www.kart-map.pl/produkt/szafa-do-segregatorow-i-teczek-wiszacych-for-a-4-3-szuflady/", "", ""),
  ("https://www.kart-map.pl/produkt/stol-montazowy-sztywny-for-a-0/", "", ""),
]