'''
1. Sprawdzić linki, poprzednia cene wpisac do pierwszego miejsca po linku
2. w drugie miejsce wpisac odpowiednik Malowa

'''

links = [
  # Szafy z drzwiami skrzydłowymi
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-O120200-RODO/547", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-O100200-czarna-znakowana-RODO/910", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-O100200-RODO/546", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-O80200-RODO/545", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-O60200-RODO/544", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-O120104/551", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-O100104-RODO/550", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-O80104/549", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-O60104/548", "", ""),
  ("https://locobox.pl/pl/p/Nadstawka-do-szafy-aktowej-PROFI-ON12081/559", "", ""),
  ("https://locobox.pl/pl/p/Nadstawka-do-szafy-aktowej-PROFI-ON10081/558", "", ""),
  ("https://locobox.pl/pl/p/Nadstawka-do-szafy-aktowej-PROFI-ON8081/557", "", ""),
  ("https://locobox.pl/pl/p/Nadstawka-do-szafy-aktowej-PROFI-ON6081/556", "", ""),
  ("https://locobox.pl/pl/p/Nadstawka-do-szafy-aktowej-PROFI-ON12046/555", "", ""),
  ("https://locobox.pl/pl/p/Nadstawka-do-szafy-aktowej-PROFI-ON10046/554", "", ""),
  ("https://locobox.pl/pl/p/Nadstawka-do-szafy-aktowej-PROFI-ON8046/553", "", ""),
  ("https://locobox.pl/pl/p/Nadstawka-do-szafy-aktowej-PROFI-ON6046/552", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-O100200-ze-skarbczykiem/569", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-O120200-ze-skarbczykiem/570", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowo-ubraniowa-PROFI-O120200u/572", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowo-ubraniowa-PROFI-O100200u/571", "", ""),
  # Szafy z drzwiami chowanymi
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-OS100200/573", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-OS100200-ze-skarbczykiem/574", "", ""),
  # Szafy z drzwiami przesuwnymi
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-OP140200/565", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-OP120200/563", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-OP100200/562", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-OP140104/568", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-OP120104/567", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-OP100104/566", "", ""),
  # Szafy z drzwiami żaluzjowymi
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-ZL100200/575", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-ZL120200/584", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowo-ubraniowa-PROFI-ZL100200u/576", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowo-ubraniowa-PROFI-ZL120200u/577", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-ZL100104/578", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-ZL120104/580", "", ""),
  ("https://locobox.pl/pl/p/Nadstawka-do-szafy-aktowej-PROFI-ZLN10046/581", "", ""),
  ("https://locobox.pl/pl/p/Nadstawka-do-szafy-aktowej-PROFI-ZLN12046/583", "", ""),
  # Szafy aktowe otwarte
  ("https://locobox.pl/pl/p/Szafa-otwarta-PROFI-OR-60200/1009", "", ""),
  ("https://locobox.pl/pl/p/Szafa-otwarta-PROFI-OR-80200/1010", "", ""),
  ("https://locobox.pl/pl/p/Szafa-otwarta-PROFI-OR-120200/1012", "", ""),
  ("https://locobox.pl/pl/p/Szafa-otwarta-PROFI-OR-60104/1013", "", ""),
  ("https://locobox.pl/pl/p/Szafa-otwarta-PROFI-OR-80104/1017", "", ""),
  ("https://locobox.pl/pl/p/Szafa-otwarta-PROFI-OR-120104/1015", "", ""),
  # Szafy aktowo-ubraniowe
  ("https://locobox.pl/pl/p/Szafa-aktowo-ubraniowa-PROFI-ZL100200u/576", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowo-ubraniowa-PROFI-ZL120200u/577", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowo-ubraniowa-PROFI-O120200u/572", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowo-ubraniowa-PROFI-O100200u/571", "", ""),
  # Szafy aktowo-kartotekowe
  ("https://locobox.pl/pl/p/Szafa-aktowo-kartotekowa-PROFI-OF2100200/1025", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowo-kartotekowa-PROFI-OF3100200/1026", "", ""),
  ("https://locobox.pl/pl/p/Szafa-aktowo-kartotekowa-PROFI-OF4100200/1027", "", ""),
  # Szafy kartotekowe Format A4
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F4xA4/1028", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F4x2A4/1029", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F2xA4/1030", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F3xA4/1062", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F5xA4/1063", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F2x2A4/1064", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F3x2A4/1065", "", ""),
  # Szafy kartotekowe Format A5
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F5x2A5/1031", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F2x2A5/1032", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F3x2A5/1033", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F4x2A5/1034", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F5x4A5/1035", "", ""),
  # Szafy kartotekowe Format A6
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F4x4A6/1036", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F6x4A6/1037", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F8x4A6/1038", "", ""),
  # Szafy kartotekowe  Format B5
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F5x2B5/1039", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F5xB5/1040", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F2x2B5/1041", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F3x2B5/1042", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F4x2B5/1043", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F6x2B5/1044", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F7x2B5/1045", "", ""),
  # Szafy kartotekowe  Format DIN A3
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F3xDinA3/1049", "", ""),
  # Szafy kartotekowe  Format DIN A4
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F2xDinA4/1046", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F3xDinA4/1047", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F4xDinA4/1048", "", ""),
  # Szafy kartotekowe  Pozostałe formaty
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F3x-71%2C5x52x63cm/1050", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F3x-71%2C5x52x63cm/1051", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F4x-71%2C5x47x63cm/1052", "", ""),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F4x-71%2C5x47x63cm/1053", "", ""),
  # Szafy ubraniowo-gospodarcze
  ("https://locobox.pl/pl/p/Szafa-gospodarcza-PROFI-M1-s51%2C5cm%2C-3P/345", "", ""),
  ("https://locobox.pl/pl/p/Szafa-gospodarcza-PROFI-M2-s51%2C5cm%2C-3P/348", "", ""),
  ("https://locobox.pl/pl/p/Szafa-gospodarcza-PROFI-M3-s51%2C5cm%2C-3P/351", "", ""),
  ("https://locobox.pl/pl/p/Szafa-gospodarcza-PROFI-M1-s60cm%2C-3P/346", "", ""),
  ("https://locobox.pl/pl/p/Szafa-gospodarcza-PROFI-M2-s60cm%2C-3P/349", "", ""),
  ("https://locobox.pl/pl/p/Szafa-gospodarcza-PROFI-M3-s60cm%2C-3P/352", "", ""),
  ("https://locobox.pl/pl/p/Szafa-gospodarcza-PROFI-M1-s80cm%2C-3P/347", "", ""),
  ("https://locobox.pl/pl/p/Szafa-gospodarcza-PROFI-M2-s80cm%2C-3P/350", "", ""),
  ("https://locobox.pl/pl/p/Szafa-gospodarcza-PROFI-M3-s80cm%2C-3P/353", "", ""),
  # Szafki na telefony
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-na-komorki-PROFI-M5/1077", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-na-komorki-PROFI-M10/1078", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-na-komorki-PROFI-M20/1079", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-na-komorki-PROFI-M30/1080", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-na-komorki-PROFI-M35/1081", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-na-komorki-PROFI-M50/1082", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-na-komorki-PROFI-M55/1083", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-na-komorki-PROFI-M60/1084", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-na-komorki-PROFI-M80/1085", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-na-komorki-PROFI-M90/1086", "", ""),
  # Szafy na laptopy i tablety
  ("https://locobox.pl/pl/p/Szafka-na-10-laptopow-z-zasilaniem-230V/337", "", ""),
  ("https://locobox.pl/pl/p/Szafka-na-10-laptopow/338", "", ""),
  ("https://locobox.pl/pl/p/Wozek-na-10-laptopow-z-zasilaniem-230V/339", "", ""),
  ("https://locobox.pl/pl/p/Wozek-na-16-laptopow-z-zasilaniem-230V/340", "", ""),
  ("https://locobox.pl/pl/p/Wozek-na-20-laptopow-z-zasilaniem-230V/341", "", ""),
  ("https://locobox.pl/pl/p/Wozek-na-26-laptopow-z-zasilaniem-230V/342", "", ""),
  ("https://locobox.pl/pl/p/Wozek-na-30-laptopow-z-zasilaniem-230V/343", "", ""),
  ("https://locobox.pl/pl/p/Szafka-na-32-tablety-i-1-laptopa-z-zasilaniem-230V/344", "", ""),
  #  Szafki śniadaniowe wiszące
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-wiszaca-PROFI-S5%2C-szer.-22%2C2cm/876", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-wiszaca-PROFI-S10%2C-szer.-41%2C5cm/877", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-wiszaca-PROFI-S15%2C-szer.-60%2C7cm/878", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-wiszaca-PROFI-S20%2C-szer.-80cm/879", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-wiszaca-PROFI-S25%2C-szer.-99%2C2cm/880", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-wiszaca-PROFI-S6%2C-szer.-39%2C3cm/881", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-wiszaca-PROFI-S12%2C-szer.-75%2C6cm/885", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-wiszaca-PROFI-S18%2C-szer.-112cm/886", "", ""),
  #  Szafki śniadaniowe stojące
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-na-stelazu-PROFI-S88%2C-szer.-22%2C2cm/887", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-na-stelazu-PROFI-S168%2C-szer.-41%2C5cm/888", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-na-stelazu-PROFI-S248%2C-szer.-60%2C7cm/890", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-na-stelazu-PROFI-S328%2C-szer.-80cm/891", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-na-stelazu-PROFI-S408%2C-szer.-99%2C2cm/892", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-na-stelazu-PROFI-S77%2C-szer.-22%2C2cm/893", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-na-stelazu-PROFI-S147%2C-szer.-41%2C5cm/894", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-na-stelazu-PROFI-S217%2C-szer.-60%2C7cm/895", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-na-stelazu-PROFI-S287%2C-szer.-80cm/896", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-na-stelazu-PROFI-S357%2C-szer.-99%2C2cm/897", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-PROFI-S99%2C-szer.-22%2C2cm/898", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-PROFI-S189%2C-szer.-41%2C5cm/899", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-PROFI-S279%2C-szer.-60%2C7cm/900", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-PROFI-S369%2C-szer.-80cm/901", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-PROFI-S459%2C-szer.-99%2C2cm/903", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-PROFI-S1010%2C-szer.-39%2C3cm/904", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-PROFI-S2010%2C-szer.-75%2C6cm/905", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-PROFI-S3010%2C-szer.-112cm/906", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-na-stelazu-PROFI-S99%2C-szer.-39%2C3cm/907", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-na-stelazu-PROFI-S189%2C-szer.-75%2C6cm/908", "", ""),
  ("https://locobox.pl/pl/p/Szafka-sniadaniowa-na-stelazu-PROFI-S279%2C-szer.-112cm/909", "", ""),
  # Szafy depozytowe  Szafki 6-drzwiowe
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B66-s31%2C5-cm%2C-h180-cm/242", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B126-s60-cm%2C-h180-cm/243", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B186-s88.%2C5-cm%2C-h180-cm/244", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B246-s117-cm%2C-h180-cm/245", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B66-s41.%2C5-cm%2C-h180-cm/246", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B126-s80-cm%2C-h180-cm/247", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B186-s118%2C5-cm%2C-h180-cm/248", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B66-s31%2C5-cm%2C-h150-cm/249", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B126-s60-cm%2C-h150-cm/250", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B186-s88%2C5-cm%2C-h150-cm/251", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B246-s117-cm%2C-h150-cm/252", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B66-s41.%2C5-cm%2C-h150-cm/253", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B126-s80-cm%2C-h150-cm/254", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B186-s118.%2C5-cm%2C-h150-cm/255", "", ""),
  # Szafy depozytowe  Szafki 3-drzwiowe z półką
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B33-s31%2C5-cm%2C-h180-cm/486", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B63-s60-cm%2C-h180-cm/464", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B93-s88.%2C5-cm%2C-h180-cm/463", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B123-s117-cm%2C-h180-cm/462", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B33-s41.%2C5-cm%2C-h180-cm/467", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B63-s80-cm%2C-h180-cm/466", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B93-s118%2C5-cm%2C-h180-cm/465", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B33-s31%2C5-cm%2C-h150-cm/487", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B63-s60-cm%2C-h150-cm/476", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B93-s88%2C5-cm%2C-h150-cm/475", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B123-s117-cm%2C-h150-cm/474", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B33-s41.%2C5-cm%2C-h150-cm/479", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B63-s80-cm%2C-h150-cm/478", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B93-s118.%2C5-cm%2C-h150-cm/477", "", ""),
  #  Szafy depozytowe  Szafki 4-drzwiowe z półką
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B44-s31%2C5-cm%2C-h180-cm/488", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B84-s60-cm%2C-h180-cm/470", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B124-s88.%2C5-cm%2C-h180-cm/469", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B164-s117-cm%2C-h180-cm/468", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B44-s41.%2C5-cm%2C-h180-cm/473", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B84-s80-cm%2C-h180-cm/472", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B124-s118%2C5-cm%2C-h180-cm/471", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B44-s31%2C5-cm%2C-h150-cm/489", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B84-s60-cm%2C-h150-cm/482", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B124-s88%2C5-cm%2C-h150-cm/481", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B164-s117-cm%2C-h150-cm/480", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B44-s41.%2C5-cm%2C-h150-cm/485", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B84-s80-cm%2C-h150-cm/484", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-z-polka-PROFI-B124-s118.%2C5-cm%2C-h150-cm/483", "", ""),
  #  Szafy depozytowe  Szafki 3-drzwiowe
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B33-s31%2C5-cm%2C-h180-cm/200", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B63-s60-cm%2C-h180-cm/201", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B93-s88.%2C5-cm%2C-h180-cm/202", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B123-s117-cm%2C-h180-cm/203", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B33-s41.%2C5-cm%2C-h180-cm/204", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B63-s80-cm%2C-h180-cm/205", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B93-s118%2C5-cm%2C-h180-cm/206", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B33-s31%2C5-cm%2C-h150-cm/207", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B63-s60-cm%2C-h150-cm/208", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B93-s88%2C5-cm%2C-h150-cm/209", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B123-s117-cm%2C-h150-cm/210", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B33-s41.%2C5-cm%2C-h150-cm/211", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B63-s80-cm%2C-h150-cm/212", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B93-s118.%2C5-cm%2C-h150-cm/213", "", ""),
  # Szafy depozytowe  Szafki 4-drzwiowe
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B44-s31%2C5-cm%2C-h180-cm/214", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B84-s60-cm%2C-h180-cm/215", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B124-s88.%2C5-cm%2C-h180-cm/216", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B164-s117-cm%2C-h180-cm/217", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B44-s41.%2C5-cm%2C-h180-cm/218", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B84-s80-cm%2C-h180-cm/219", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B124-s118%2C5-cm%2C-h180-cm/220", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B44-s31%2C5-cm%2C-h150-cm/221", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B84-s60-cm%2C-h150-cm/222", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B124-s88%2C5-cm%2C-h150-cm/223", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B164-s117-cm%2C-h150-cm/224", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B44-s41.%2C5-cm%2C-h150-cm/225", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B84-s80-cm%2C-h150-cm/226", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B124-s118.%2C5-cm%2C-h150-cm/227", "", ""),
  # Szafy depozytowe  Szafki 5-drzwiowe
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B55-s31%2C5-cm%2C-h180-cm/228", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B105-s60-cm%2C-h180-cm/229", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B155-s88.%2C5-cm%2C-h180-cm/230", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B205-s117-cm%2C-h180-cm/231", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B55-s41.%2C5-cm%2C-h180-cm/232", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B105-s80-cm%2C-h180-cm/233", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B155-s118%2C5-cm%2C-h180-cm/234", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B55-s31%2C5-cm%2C-h150-cm/235", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B105-s60-cm%2C-h150-cm/236", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B155-s88%2C5-cm%2C-h150-cm/237", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B205-s117-cm%2C-h150-cm/238", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B55-s41.%2C5-cm%2C-h150-cm/239", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B105-s80-cm%2C-h150-cm/240", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B155-s118.%2C5-cm%2C-h150-cm/241", "", ""),
  # Ławki korytarzowe
  ("https://locobox.pl/pl/p/Lawka-wolnostojaca-PROFI-L100/525", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wolnostojaca-PROFI-L120/519", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wolnostojaca-PROFI-L140/520", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wolnostojaca-PROFI-L150/521", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wolnostojaca-PROFI-L160/522", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wolnostojaca-PROFI-L180/523", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wolnostojaca-PROFI-L200/524", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wolnostojaca-PROFI-L60/517", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wolnostojaca-PROFI-L90/518", "", ""),
  #  Podstawy pod szafki niskie
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-niska-PROFI-LN100/542", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-niska-PROFI-LN115/543", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-niska-PROFI-LN120/538", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-niska-PROFI-LN30/535", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-niska-PROFI-LN40/539", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-niska-PROFI-LN50/541", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-niska-PROFI-LN60/536", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-niska-PROFI-LN80/540", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-niska-PROFI-LN90/537", "", ""),
  # Podstawy pod szafki wysokie
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-PROFI-L100/533", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-PROFI-L115/534", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-PROFI-L120/529", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-PROFI-L30/526", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-PROFI-L40/530", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-PROFI-L50/532", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-PROFI-L60/527", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-PROFI-L80/531", "", ""),
  ("https://locobox.pl/pl/p/Podstawa-pod-szafki-bez-lawki-PROFI-L90/528", "", ""),
  # Nóżki
  ("https://locobox.pl/pl/p/Nozki-do-szaf-socjalnych-o-wys.-10cm/437", "", ""),
  #  Skośne daszki
  ("https://locobox.pl/pl/p/Daszek-PROFI-D/429", "", ""),
  # Zamki do szafek
  ("https://locobox.pl/pl/p/Zamek-elektroniczny-na-karty-RFID/1095", "", ""),
  ("https://locobox.pl/pl/p/Zamek-na-klucz/368", "", ""),
  ("https://locobox.pl/pl/p/Zamek-klodkowy-20-mm-chrom/370", "", ""),
  ("https://locobox.pl/pl/p/Zamek-klodkowy-cylinder-25-mm-czarny/371", "", ""),
  ("https://locobox.pl/pl/p/Zamek-klodkowy-360st-30-mm-chrom/369", "", ""),
  ("https://locobox.pl/pl/p/Zamek-depozytowy-na-2zl%2C-lewy-wezowy/376", "", ""),
  ("https://locobox.pl/pl/p/Zamek-depozytowy-na-2zl%2C-prawy-wezowy/379", "", ""),
  ("https://locobox.pl/pl/p/Cylinder-do-zamka-depozytowego-wezowego/372", "", ""),
  ("https://locobox.pl/pl/p/Rozetka-do-zamka-depozytowego/375", "", ""),
  ("https://locobox.pl/pl/p/Zamek-szyfrowy-lewy-M224-z-ryglem-czarny/395", "", ""),
  ("https://locobox.pl/pl/p/Zamek-szyfrowy-prawy-M224-z-ryglem-czarny/400", "", ""),
  ("https://locobox.pl/pl/p/Plytka-montazowa-zamka-M224-metal/456", "", ""),
  ("https://locobox.pl/pl/p/Plytka-montazowa-zamka-M224-drewno/386", "", ""),
  ("https://locobox.pl/pl/p/Zamek-szyfrowy-EURO-LOCK/404", "", ""),
  ("https://locobox.pl/pl/p/Klodka-szyfrowa-czarna/385", "", ""),
  ("https://locobox.pl/pl/p/Zamek-szyfrowy-uniwersalny/402", "", ""),
  ("https://locobox.pl/pl/p/Zamek-szyfrowy-elektroniczny-MARC-PUBLICZNY/458", "", ""),
  ("https://locobox.pl/pl/p/Zamek-szyfrowy-elektroniczny-MARC-PRYWATNY/457", "", ""),
  ("https://locobox.pl/pl/p/Oslona-zamka-MARC-czarna-stal/459", "", ""),
  ("https://locobox.pl/pl/p/Ladowarka-do-zamka-elektronicznego-PUBLIC/426", "", ""),
  ("https://locobox.pl/pl/p/Chip-Zamek-elektroniczny-Proxy/420", "", ""),
  ("https://locobox.pl/pl/p/Chip-Zaczep-drzwi-przesuwnych/418", "", ""),
  ("https://locobox.pl/pl/p/Chip-Zaczep-sprezynowy-PTO/419", "", ""),
  ("https://locobox.pl/pl/p/Chip-klucz-na-bransoletce-czarnej/416", "", ""),
  ("https://locobox.pl/pl/p/Chip-klucz-na-bransoletce-czerwonej/417", "", ""),
  ("https://locobox.pl/pl/p/Chip-klucz-bialy/415", "", ""),
  ("https://locobox.pl/pl/p/Chip-karta-programujaca/414", "", ""),
  ("https://locobox.pl/pl/p/Chip-Antena-MINI-ROD-z-1%2C5m-kablem/411", "", ""),
  ("https://locobox.pl/pl/p/Chip-Antena-z-1%2C5m-kablem/412", "", ""),
  ("https://locobox.pl/pl/p/Chip-Bateria-litowa/413", "", ""),
  # Szafki ubraniowe BHP Szafki standardowe
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U2-s60-cm/284", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U3-s88%2C5-cm/285", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U4-s117-cm/286", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U1-s41%2C5-cm/287", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U2-s80-cm/288", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U3-s118%2C5-cm/289", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U1-s51%2C5-cm/290", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U2-s100-cm/291", "", ""),
  # Szafki ubraniowe BHP  Szafki standardowe z półką
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U1-z-polka-na-buty-s31%2C5-cm/292", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U2-z-polka-na-buty-s60-cm/293", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U3-z-polka-na-buty-s88%2C5-cm/294", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U4-z-polka-na-buty-s117-cm/295", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U1-z-polka-na-buty-s41%2C5-cm/296", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U2-z-polka-na-buty-s80-cm/297", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U3-z-polka-na-buty-s118%2C5-cm/298", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U1-z-polka-na-buty-s51%2C5-cm/299", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U2-z-polka-na-buty-s100-cm/300", "", ""),
  # Szafki ubraniowe BHP  Szafki z podziałem
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT1-s31%2C5-cm/307", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT2-s60-cm/308", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT3-s88%2C5-cm/309", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT4-s117-cm/310", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT1-s41%2C5-cm/301", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT2-s80-cm/302", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT3-s118%2C5-cm/303", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT1-s51%2C5-cm/315", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT2-s100-cm/316", "", ""),
  # Szafki ubraniowe BHP  Szafki z podziałem i półką
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT1-z-polka-na-buty-s31%2C5-cm/311", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT2-z-polka-na-buty-s60-cm/312", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT3-z-polka-na-buty-s88%2C5-cm/313", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT4-z-polka-na-buty-s117-cm/314", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT1-z-polka-na-buty-s41%2C5-cm/304", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT2-z-polka-na-buty-s80-cm/305", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT3-z-polka-na-buty-s118%2C5-cm/306", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT1-z-polka-na-buty-s51%2C5-cm/317", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-UT2-z-polka-na-buty-s100-cm/318", "", ""),
  # Szafki z drzwiami "L"
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-L2-s31%2C5-cm/322", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-L4-s60-cm/323", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-L6-s88%2C5-cm/324", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-L8-s117-cm/1099", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-L2-s41%2C5-cm/319", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-L4-s80-cm/320", "", ""),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-L6-s118%2C5-cm/321", "", ""),
  # Szafki skrytkowo-ubraniowe
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B22-s31%2C5-cm%2C-h180-cm/186", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B42-s60-cm%2C-h180-cm/187", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B62-s88%2C5-cm%2C-h180-cm/188", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B82-s117-cm%2C-h180-cm/189", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B102-s145%2C5-cm%2C-h180-cm/1120", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B22-s31%2C5-cm%2C-h150cm/193", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B42-s60-cm%2C-h150cm/194", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B62-s88%2C5-cm%2C-h150cm/195", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B82-s117-cm%2C-h150cm/196", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B102-s145%2C5-cm%2C-h150cm/1121", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B22-s41%2C5-cm%2C-h180-cm/190", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B42-s80-cm%2C-h180-cm/191", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B62-s118%2C5-cm%2C-h180-cm/192", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B82-s157-cm%2C-h180-cm/1122", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B22-s41%2C5-cm%2C-h150cm/197", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B42-s80-cm%2C-h150cm/198", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B62-s118%2C5-cm%2C-h150cm/199", "", ""),
  ("https://locobox.pl/pl/p/Szafka-skrytkowa-PROFI-B82-s157-cm%2C-h150cm/1123", "", ""),
  # Szafki strażackie
  ("https://locobox.pl/pl/p/Szafa-strazacka-1-kolumnowa-F1/991", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-1-kolumnowa-F1-na-nozkach/992", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-2-kolumnowa-F1/993", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-2-kolumnowa-F1-na-nozkach/994", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-3-kolumnowa-F1/995", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-3-kolumnowa-F1-na-nozkach/996", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-1-kolumnowa-F1_5/997", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-1-kolumnowa-F1_5-na-nozkach/998", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-2-kolumnowa-F1_5/999", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-2-kolumnowa-F1_5-na-nozkach/1000", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-3-kolumnowa-F1_5/1001", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-3-kolumnowa-F1_5-na-nozkach/1002", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-1-kolumnowa-F1_8/1003", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-1-kolumnowa-F1_8-na-nozkach/1004", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-2-kolumnowa-F1_8/1005", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-2-kolumnowa-F1_8-na-nozkach/1006", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-3-kolumnowa-F1_8/1007", "", ""),
  ("https://locobox.pl/pl/p/Szafa-strazacka-3-kolumnowa-F1_8-na-nozkach/1008", "", ""),
  # Szafki do wydawania odzieży roboczej
  ("https://locobox.pl/pl/p/Szafa-na-odziez-czysta-PROFI-CC55/981", "", ""),
  ("https://locobox.pl/pl/p/Szafa-na-odziez-czysta-PROFI-CC105/982", "", ""),
  ("https://locobox.pl/pl/p/Szafa-na-odziez-czysta-PROFI-CC1010/983", "", ""),
  ("https://locobox.pl/pl/p/Szafa-na-odziez-czysta-PROFI-CC2010/984", "", ""),
  ("https://locobox.pl/pl/p/Szafa-na-odziez-brudna-PROFI-DC-10/985", "", ""),
  ("https://locobox.pl/pl/p/Szafa-na-odziez-czysta-PROFI-CC1111/986", "", ""),
  ("https://locobox.pl/pl/p/Szafa-na-odziez-czysta-PROFI-CC2211/987", "", ""),
  ("https://locobox.pl/pl/p/Szafa-na-odziez-czysta-i-brudna-CC1111-DC/988", "", ""),
  ("https://locobox.pl/pl/p/Szafa-na-odziez-czysta-i-brudna-CC2211-DC/989", "", ""),
  ("https://locobox.pl/pl/p/Szafa-na-odziez-brudna-PROFI-DC-11/990", "", ""),
  # Podstawy pod szafki z ławką stałą
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-pod-szafy-s120-cm-4K/117", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-pod-szafy-s120-cm-3K/120", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-polka-na-buty-pod-szafy-s120-cm-4K/126", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-polka-na-buty-pod-szafy-s120-cm-3K/129", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-polka-na-buty-pod-szafy-s100-cm-2K/131", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-ze-skrytka-na-buty-pod-szafy-s120-cm-4K/135", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-ze-skrytka-na-buty-pod-szafy-s120-cm-3K/138", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-ze-skrytka-na-buty-pod-szafy-s100-cm-2K/140", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-zamykana-skrytka-na-buty-pod-szafy-s120-cm-4K/144", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-zamykana-skrytka-na-buty-pod-szafy-s120-cm-3K/147", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-zamykana-skrytka-na-buty-pod-szafy-s100-cm-2K/149", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-pod-szafy-s90-cm-3K/116", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-pod-szafy-s80-cm-2K/119", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-pod-szafy-s50-cm-1K/121", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-polka-na-buty-pod-szafy-s90-cm-3K/125", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-polka-na-buty-pod-szafy-s80-cm-2K/128", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-polka-na-buty-pod-szafy-s50-cm-1K/130", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-ze-skrytka-na-buty-pod-szafy-s90-cm-3K/134", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-ze-skrytka-na-buty-pod-szafy-s80-cm-2K/137", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-ze-skrytka-na-buty-pod-szafy-s50-cm-1K/139", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-zamykana-skrytka-na-buty-pod-szafy-s90-cm-3K/143", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-zamykana-skrytka-na-buty-pod-szafy-s80-cm-2K/146", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-zamykana-skrytka-na-buty-pod-szafy-s50-cm-1K/148", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-pod-szafy-s60-cm-2K/115", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-pod-szafy-s40-cm-1K/118", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-pod-szafy-s30-cm-1K/114", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-polka-na-buty-pod-szafy-s60-cm-2K/124", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-polka-na-buty-pod-szafy-s40-cm-1K/127", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-polka-na-buty-pod-szafy-s30-cm-1K/123", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-ze-skrytka-na-buty-pod-szafy-s60-cm-2K/133", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-ze-skrytka-na-buty-pod-szafy-s40-cm-1K/136", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-ze-skrytka-na-buty-pod-szafy-s30-cm-1K/132", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-zamykana-skrytka-na-buty-pod-szafy-s60-cm-2K/142", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-zamykana-skrytka-na-buty-pod-szafy-s40-cm-1K/145", "", ""),
  ("https://locobox.pl/pl/p/Lawka-stala-PROFI-LS-z-zamykana-skrytka-na-buty-pod-szafy-s30-cm-1K/141", "", ""),
  # Podstawy pod szafki z ławką wysuwaną
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-pod-szafy-s120-cm-4K/153", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-pod-szafy-s120-cm-3K/156", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-pod-szafy-s100-cm-2K/158", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-polka-na-buty-pod-szafy-s120-cm-4K/162", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-polka-na-buty-pod-szafy-s120-cm-3K/165", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-polka-na-buty-pod-szafy-s100-cm-2K/167", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-ze-skrytka-na-buty-pod-szafy-s120-cm-4K/171", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-ze-skrytka-na-buty-pod-szafy-s120-cm-3K/174", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-ze-skrytka-na-buty-pod-szafy-s100-cm-2K/176", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-zamykana-skrytka-na-buty-pod-szafy-s120-cm-4K/180", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-zamykana-skrytka-na-buty-pod-szafy-s120-cm-3K/183", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-zamykana-skrytka-na-buty-pod-szafy-s100-cm-2K/185", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-pod-szafy-s90-cm-3K/152", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-pod-szafy-s80-cm-2K/155", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-pod-szafy-s50-cm-1K/157", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-polka-na-buty-pod-szafy-s90-cm-3K/161", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-polka-na-buty-pod-szafy-s80-cm-2K/164", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-polka-na-buty-pod-szafy-s50-cm-1K/166", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-ze-skrytka-na-buty-pod-szafy-s90-cm-3K/170", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-ze-skrytka-na-buty-pod-szafy-s80-cm-2K/173", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-ze-skrytka-na-buty-pod-szafy-s50-cm-1K/175", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-zamykana-skrytka-na-buty-pod-szafy-s90-cm-3K/179", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-zamykana-skrytka-na-buty-pod-szafy-s80-cm-2K/182", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-zamykana-skrytka-na-buty-pod-szafy-s50-cm-1K/184", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-pod-szafy-s60-cm-2K/151", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-pod-szafy-s40-cm-1K/154", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-pod-szafy-s30-cm-1K/150", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-polka-na-buty-pod-szafy-s60-cm-2K/160", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-polka-na-buty-pod-szafy-s40-cm-1K/163", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-polka-na-buty-pod-szafy-s30-cm-1K/159", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-ze-skrytka-na-buty-pod-szafy-s60-cm-2K/169", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-ze-skrytka-na-buty-pod-szafy-s40-cm-1K/172", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-ze-skrytka-na-buty-pod-szafy-s30-cm-1K/168", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-zamykana-skrytka-na-buty-pod-szafy-s60-cm-2K/178", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-zamykana-skrytka-na-buty-pod-szafy-s40-cm-1K/181", "", ""),
  ("https://locobox.pl/pl/p/Lawka-wysuwana-PROFI-LR-z-zamykana-skrytka-na-buty-pod-szafy-s30-cm-1K/177", "", ""),
]


links = [
  ("https://locobox.pl/pl/p/Szafka-szkolna-dla-4-uczniow-4D-s60-cm%2C-h180-cm/257", "628", "Sus 322 W"),
  ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U2-s60-cm/284", "449", "Sum 320 W"),
  # ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-U2-s80-cm/288", "583", "Sum 420 W"),
  # ("https://locobox.pl/pl/p/Szafa-ubraniowa-PROFI-L4-s60-cm/323", "1013", "Sul 32 W"),
  # ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-O80200-RODO/545", "855", "Sbm 202 M"),
  # ("https://locobox.pl/pl/p/Szafa-aktowa-PROFI-O80200-RODO/545", "905", "Sbm 203 M"),
  ("https://locobox.pl/pl/p/Szafa-kartotekowa-PROFI-F4xA4/1028", "775", "Szk 301"),
  ("https://locobox.pl/pl/p/Szafa-gospodarcza-PROFI-M3-s80cm%2C-3P/353", "", ""),
]