
links = [
 # Meble socjalne » Szafy ubraniowe bhp
 ("https://umstahl.pl/metalowa-szafka-ubraniowa-se-25r2-24h,id960.html", "546", "SUM"),
 ("https://umstahl.pl/metalowa-szafka-ubraniowa-se-30r2-24h,id102.html", "566", "SUM 320"),
 ("https://umstahl.pl/metalowa-szafka-ubraniowa-profi-zm-u60,id1065.html", "497", "SUM 320"),
 ("https://umstahl.pl/metalowa-szafka-ubraniowa-profi-zm-u80,id1149.html", "601", "SUM 320"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-z-podzialem-wewnetrznym-se-40r2-24h,id550.html", "776", "SUM 420"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-se-30r2-law-ste-600,id987.html", "792", "SUM"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-sle-40r2-24h,id104.html", "1024", "SUL 42"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-cp-duq-60,id659.html", "892", "SUM 320"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-cp-duq-61,id857.html", "809", "SUM 320"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-cp-duq-80,id660.html", "1063", "SUM 420"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-cp-duq-812,id859.html", "916", "SUM 420"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-se-30r1,id190.html", "547", "SUM 310"),
 ("https://umstahl.pl/metalowa-szafka-ubraniowa-se-25r2,id1094.html", "", "SUM"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-se-30r2,id548.html", "797", "SUM 320"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-se-30r3,id191.html", "", "SUM"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-se-30r4,id192.html", "", "SUM"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-z-podzialem-wewnetrznym-se-40r1,id193.html", "", "SUM"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-z-podzialem-wewnetrznym-se-40r2,id103.html", "978", "SUM 420"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-z-podzialem-wewnetrznym-se-40r3,id194.html", "1591", "SUM 330"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-sle-30r1,id402.html", "777", "SUL 31"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-sle-30r2,id403.html", "1322", "SUL 32"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-sle-30r3,id404.html", "1987", "SUL 33"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-sle-30r4,id658.html", "2735", "SUL 34"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-sle-40r1,id405.html", "862", "SUL 41"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-sle-40r2,id549.html", "1447", "SUL 42"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-sle-40r3,id406.html", "2113", "SUL 43"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-su-30r1,id41.html", "613", "SUM 310"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-su-30r2,id42.html", "939", "SUM 320"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-su-30r3,id43.html", "1379", "SUM 330"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-su-30r4,id44.html", "1869", "SUM 340"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-z-podzialem-wewnetrznym-su-40r1,id45.html", "709", "SUM 410"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-z-podzialem-wewnetrznym-su-40r2,id46.html", "1149", "SUM 420"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-z-podzialem-wewnetrznym-su-40r3,id47.html", "1725", "SUM 430"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-sl-30r1,id195.html", "873", "SUL 31"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-sl-30r2,id196.html", "1427", "SUL 32"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-sl-30r3,id197.html", "2128", "SUL 33"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-sl-40r1,id39.html", "978", "SUL 41"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-sl-40r2,id40.html", "1581", "SUL 42"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-sl-40r3,id198.html", "2233", "SUL 43"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-do-przechowywania-odziezy-czystej-sc-10r1,id98.html", "1155", "MKB 4"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-do-przechowywania-odziezy-czystej-sc-10r2,id99.html", "1947", "MKB 2"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-do-przechowywania-odziezy-czystej-sc-5r1,id100.html", "", "MKB"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-do-przechowywania-odziezy-czystej-sc-12r2,id189.html", "", "MKB"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-do-przechowywania-odziezy-czystej-sc-5r2,id101.html", "", "MKB"),
 ("https://umstahl.pl/metalowa-szafa-wrzutowa-na-odziez-brudna-sb,id97.html", "704", "MKB 5E"),
 # Meble socjalne » Szafy wirusobójcze
 ("https://umstahl.pl/wirusobojcza-szafa-ubraniowa-uv-c-2-modulowa-1-95300-441,id980.html", "", "SUM"),
 ("https://umstahl.pl/wirusobojcza-szafa-ubraniowa-uv-c-3-modulowa-1-95301-441,id981.html", "", "SUM"),
 # Meble socjalne » Szafy skrytkowe
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-dsq-61,id860.html", "945", "SUS 320"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-dsq-60,id665.html", "945", "SUS 320"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-23r1,id354.html", "589", "SUS 312"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-23r2,id355.html", "837", "SUS 322"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-23r3,id356.html", "1212", "SUS 332"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-23r4,id357.html", "1545", "SUS 342"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-23r5,id358.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-24r1,id359.html", "640", "SUS 412"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-24r2,id360.html", "956", "SUS 422"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-24r3,id361.html", "1383", "SUS 432"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-25r1,id741.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-25r2,id742.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-25r3,id743.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-25r4,id744.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-25r5,id745.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-33r1,id362.html", "598", "SUS 313"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-33r3,id472.html", "1349", "SUS 333"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-33r2,id363.html", "999", "SUS 323"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-33r4,id364.html", "1767", "SUS 343"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-34r1,id365.html", "666", "SUS 413"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-34r2,id366.html", "1076", "SUS 423"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-34r3,id367.html", "1469", "SUS 433"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-43r1,id368.html", "675", "SUS 314"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-43r2,id369.html", "1110", "SUS 324"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-43r3,id370.html", "1554", "SUS 334"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-43r4,id471.html", "2024", "SUS 344"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-44r1,id371.html", "743", "SUS 414"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-44r2,id372.html", "1212", "SUS 424"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-44r3,id373.html", "1648", "SUS 434"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-53r1,id374.html", "726", "SUS 315"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-53r2,id375.html", "1178", "SUS 325"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-53r3,id376.html", "1733", "SUS 335"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-53r4,id469.html", "2263", "SUS 345"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-54r1,id377.html", "794", "SUS 415"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-54r2,id378.html", "1349", "SUS 425"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-54r3,id379.html", "1836", "SUS 435"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-63r1,id380.html", "828", "SUS 316"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-63r2,id381.html", "1340", "SUS 326"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-63r3,id382.html", "1930", "SUS 336"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-63r4,id470.html", "2536", "SUS 346"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-64r1,id383.html", "920", "SUS 416"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-64r3,id385.html", "2041", "SUS 436"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ssm-64r2,id384.html", "1537", "SUS 426"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-23r3,id15.html", "1738", "SUS 332"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-23r2,id14.html", "1123", "SUS 322"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-23r1,id13.html", "787", "SUS 312"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-24r1,id25.html", "845", "SUS 412"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-24r2,id26.html", "1258", "SUS 422"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-24r3,id27.html", "1891", "SUS 433"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-33r1,id16.html", "835", "SUS 313"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-33r2,id17.html", "1354", "SUS 323"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-33r3,id18.html", "1862", "SUS 333"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-34r1,id28.html", "902", "SUS 413"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-34r2,id29.html", "1411", "SUS 423"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-34r3,id30.html", "1949", "SUS 433"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-43r1,id19.html", "893", "SUS 314"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-43r2,id20.html", "1469", "SUS 324"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-43r3,id21.html", "2064", "SUS 334"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-44r1,id31.html", "989", "SUS 414"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-44r2,id32.html", "1594", "SUS 424"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-44r3,id33.html", "2170", "SUS 434"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-53r1,id22.html", "989", "SUS 315"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-53r2,id23.html", "1565", "SUS 325"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-53r3,id24.html", "2285", "SUS 335"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-54r1,id34.html", "1114", "SUS 415"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-54r2,id35.html", "1786", "SUS 425"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-54r3,id36.html", "2429", "SUS 435"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-63r1,id183.html", "1094", "SUS 316"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-63r2,id184.html", "1786", "SUS 326"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-63r3,id185.html", "2554", "SUS 336"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-64r1,id186.html", "1200", "SUS 416"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-64r2,id187.html", "2026", "SUS 426"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-ss-64r3,id188.html", "2698", "SUS 436"),
 # Meble socjalne » Szafy śniadaniowe
 ("https://umstahl.pl/metalowa-szafa-sniadaniowa-wiszaca-5-skrytkowa-1-kolumnowa-ssnw-5r1,id452.html", "592", "WSS 05"),
 ("https://umstahl.pl/metalowa-szafa-sniadaniowa-wiszaca-10-skrytkowa-2-kolumnowa-ssnw-5r2,id453.html", "873", "WSS 10"),
 ("https://umstahl.pl/metalowa-szafa-sniadaniowa-wiszaca-15-skrytkowa-3-kolumnowa-ssnw-5r3,id454.html", "1212", "WSS 15"),
 ("https://umstahl.pl/metalowa-szafa-sniadaniowa-wiszaca-20-skrytkowa-4-kolumnowa-ssnw-5r4,id455.html", "1693", "WSS 20"),
 ("https://umstahl.pl/metalowa-szafa-sniadaniowa-wiszaca-25-skrytkowa-5-kolumnowa-ssnw-5r5,id456.html", "1996", "WSS 25"),
 ("https://umstahl.pl/metalowa-szafa-sniadaniowa-10-skrytkowa-1-kolumnowa-ssn-10r1,id294.html", "1146", "SUS 4110"),
 ("https://umstahl.pl/metalowa-szafa-sniadaniowa-20-skrytkowa-2-kolumnowa-ssn-10r2,id295.html", "2042", "SUS 3210"),
 ("https://umstahl.pl/metalowa-szafa-sniadaniowa-30-skrytkowa-3-kolumnowa-ssn-10r3,id296.html", "2960", "SUS 4310"),
 ("https://umstahl.pl/metalowa-szafa-sniadaniowa-18-skrytkowa-2-kolumnowa-ssn-9r2,id297.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-sniadaniowa-27-skrytkowa-3-kolumnowa-ssn-9r3,id298.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-sniadaniowa-36-skrytkowa-4-kolumnowa-ssn-9r4,id299.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-sniadaniowa-45-skrytkowa-5-kolumnowa-ssn-9r5,id300.html", "", "SUS"),
 ("https://umstahl.pl/szafa-sniadaniowa-rssn-9r3-rfid,id643.html", "7417", "WSS"),
 # Meble socjalne » Szafy gospodarcze
 ("https://umstahl.pl/metalowa-szafa-gospodarcza-sgp-60-24h,id982.html", "668", "MSU 60"),
 ("https://umstahl.pl/metalowa-szafa-gospodarcza-sg80-24h,id546.html", "936", "MSU 82"),
 ("https://umstahl.pl/metalowa-szafa-gospodarcza-sg60-24h,id545.html", "737", "MSU 62"),
 ("https://umstahl.pl/metalowa-szafa-gospodarcza-sg60,id37.html", "1076", "MSU 62"),
 ("https://umstahl.pl/metalowa-szafa-gospodarcza-sg80,id38.html", "1205", "MSU 82"),
 ("https://umstahl.pl/metalowa-szafa-gospodarcza-sgp-60,id175.html", "1049", "MSU 60"),
 ("https://umstahl.pl/metalowa-szafa-gospodarcza-sgp-80,id176.html", "1168", "MSU 80"),
 ("https://umstahl.pl/metalowa-szafa-gospodarczo-ubraniowa-sgu-60,id177.html", "1095", "MSU 61"),
 ("https://umstahl.pl/metalowa-szafa-gospodarczo-ubraniowa-sgu-80,id178.html", "1224", "MSU 81"),
 # Meble socjalne » Szafki na telefony
 ("https://umstahl.pl/metalowa-szafa-na-komorki-szt-5r2,id587.html", "", ""),
 ("https://umstahl.pl/metalowa-szafa-na-komorki-szt-5r4,id588.html", "", ""),
 ("https://umstahl.pl/metalowa-szafa-na-komorki-szt-5r7,id589.html", "", ""),
 # Meble socjalne » Szafy szkolne
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-sse-25r5,id722.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-23r5,id488.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-25r5,id1097.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szkolna-szafa-skrytkowa-cp-dsq-61,id876.html", "945", "SUS 322"),
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssm-25r5n,id723.html", "", "MSUSS"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-25r1,id724.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-25r2,id725.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-25r3,id726.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-25r4,id727.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-23r1,id484.html", "589", "SUS 312"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-23r2,id485.html", "837", "SUS 322"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-23r3,id486.html", "1212", "SUS 332"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-23r4,id487.html", "1545", "SUS 342"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-24r1,id489.html", "640", "SUS 412"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowo-ubraniowa-ssm-24r2,id490.html", "956", "SUS 422"),
 ("https://umstahl.pl/metalowa-szafa-szkolna-skrytkowa-ssm-24r3,id491.html", "1383", "SUS 432"),
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssm-25r1n,id728.html", "", "MSUSS"),
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssm-25r2n,id729.html", "", "MSUSS"),
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssm-25r3n,id730.html", "", "MSUSS"),
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssm-25r4n,id731.html", "", "MSUSS"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-szkolna-sus-25r1,id179.html", "", "SUM"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-szkolna-sus-25r2,id180.html", "", "SUM"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-szkolna-sus-25r3,id181.html", "", "SUM"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-szkolna-sus-25r4,id182.html", "", "SUM"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-szkolna-sus-25r1n,id768.html", "", "MSUMS"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-szkolna-sus-25r2n,id769.html", "", "MSUMS"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-szkolna-sus-25r3n,id770.html", "", "MSUMS"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-szkolna-sus-25r4n,id771.html", "", "MSUMS"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-szkolna-ssp-23r1,id7.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-szkolna-ssp-23r2,id8.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-szkolna-ssp-23r3,id9.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-szkolna-ssk-23r1,id10.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-szkolna-ssk-23r2,id11.html", "", "SUS"),
 ("https://umstahl.pl/metalowa-szafa-skrytkowa-szkolna-ssk-23r3,id12.html", "", "SUS"),
 ("https://umstahl.pl/szafa-szkolna-ubraniowa-z-polka-na-ksiazki-sus-30r1,id1.html", "691", "SUM 310"),
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-szkolna-sus-30r2,id3.html", "1066", "SUM 320"),
 ("https://umstahl.pl/szafa-szkolna-ubraniowa-z-polka-na-ksiazki-sus-30r3,id5.html", "1613", "SUM 330"),
 ("https://umstahl.pl/szafa-szkolna-ubraniowa-z-polka-na-ksiazki-sus-30r1n,id2.html", "672", "MSUM 310S"),
 ("https://umstahl.pl/szafa-szkolna-ubraniowa-z-polka-na-ksiazki-sus-30r2n,id4.html", "1008", "MSUM 320S"),
 ("https://umstahl.pl/szafa-szkolna-ubraniowa-z-polka-na-ksiazki-sus-30r3n,id6.html", "1536", "MSUM 330S"),
 # Meble socjalne » Szafy przedszkolne
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssm-25r5n,id732.html", "", "MSUSS"),
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssm-25r1n,id733.html", "", "MSUSS"),
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssm-25r2n,id734.html", "", "MSUSS"),
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssm-25r3n,id735.html", "", "MSUSS"),
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssm-25r4n,id736.html", "", "MSUSS"),
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssp-23r1n,id304.html", "", "MSUSS"),
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssp-23r2n,id305.html", "", "MSUSS"),
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssp-23r3n,id306.html", "", "MSUSS"),
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssk-23r1n,id301.html", "", "MSUSS"),
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssk-23r2n,id302.html", "", "MSUSS"),
 ("https://umstahl.pl/metalowa-szafa-przedszkolna-skrytkowa-ssk-23r3n,id303.html", "", "MSUSS"),
 # Meble socjalne » Szafy strażackie
 ("https://umstahl.pl/metalowa-szafa-strazacka-sstr-40r2,id1091.html", "2016", "SUS 42"),
 ("https://umstahl.pl/metalowa-szafa-strazacka-sstr-40r1,id173.html", "1219", "SUS 41"),
 ("https://umstahl.pl/metalowa-szafa-strazacka-sstr-40r2,id174.html", "2016", "SUS 42"),
 # Meble socjalne » Szafy sportowe
 ("https://umstahl.pl/metalowa-szafa-na-sprzet-sportowy-s-2ola-s,id529.html", "", "SBM Sportowa"),
 ("https://umstahl.pl/metalowa-szafa-na-sprzet-sportowy-s-2ola-sp,id528.html", "", "SBM Sportowa"),
 ("https://umstahl.pl/metalowa-szafa-na-sprzet-sportowy-s-2ola-800-4p,id526.html", "", "SBM Sportowa"),
 ("https://umstahl.pl/metalowa-szafa-na-sprzet-sportowy-s-2ola-800-4,id525.html", "", "SBM Sportowa"),
 ("https://umstahl.pl/metalowa-szafa-na-sprzet-sportowy-s-2ola-1500-4,id156.html", "", "SBM Sportowa"),
 ("https://umstahl.pl/metalowa-szafa-na-sprzet-sportowy-s-2ola-1500-4p,id157.html", "", "SBM Sportowa"),
 ("https://umstahl.pl/metalowa-szafa-na-sprzet-sportowy-s-2ola-1500-s,id158.html", "", "SBM Sportowa"),
 ("https://umstahl.pl/metalowa-szafa-na-sprzet-sportowy-s-2ola-1500-sp,id159.html", "", "SBM Sportowa"),
 ("https://umstahl.pl/metalowa-szafa-na-sprzet-sportowy-s-2ola-3p,id532.html", "", "SBM Sportowa"),
 ("https://umstahl.pl/metalowa-szafa-na-sprzet-sportowy-s-2ola-3,id531.html", "", "SBM Sportowa"),
 # Meble socjalne » Szafy na paczki
 ("https://umstahl.pl/szafa-na-paczki,id977.html", "", ""),
 ("https://umstahl.pl/szafa-na-paczki-snp-2,id978.html", "", ""),
 # Meble socjalne » Ławki
 ("https://umstahl.pl/laweczka-wolnostojaca-lw600,id111.html", "", "ŁSZ"),
 ("https://umstahl.pl/laweczka-wolnostojaca-lw900,id112.html", "355", "ŁSZ 3"),
 ("https://umstahl.pl/laweczka-wolnostojaca-lw1200,id105.html", "", "ŁSZ"),
 ("https://umstahl.pl/laweczka-wolnostojaca-lw1400,id106.html", "", "ŁSZ"),
 ("https://umstahl.pl/laweczka-wolnostojaca-lw1500,id107.html", "480", "ŁSZ 3A"),
 ("https://umstahl.pl/laweczka-wolnostojaca-lw1600,id108.html", "", "ŁSZ"),
 ("https://umstahl.pl/laweczka-wolnostojaca-lw1800,id109.html", "", "ŁSZ"),
 ("https://umstahl.pl/laweczka-wolnostojaca-lw2000,id110.html", "", "ŁSZ"),
 ("https://umstahl.pl/laweczka-wolnostojaca-z-polka-na-buty-lw600p,id141.html", "", "ŁSZ"),
 ("https://umstahl.pl/laweczka-wolnostojaca-z-polka-na-buty-lw900p,id142.html", "", "ŁSZ"),
 ("https://umstahl.pl/laweczka-wolnostojaca-z-polka-na-buty-lw1200p,id135.html", "", "ŁSZ"),
 ("https://umstahl.pl/laweczka-wolnostojaca-z-polka-na-buty-lw1400p,id136.html", "", "ŁSZ"),
 ("https://umstahl.pl/laweczka-wolnostojaca-z-polka-na-buty-lw1500p,id137.html", "", "ŁSZ"),
 ("https://umstahl.pl/laweczka-wolnostojaca-z-polka-na-buty-lw1600p,id138.html", "", "ŁSZ"),
 ("https://umstahl.pl/laweczka-wolnostojaca-z-polka-na-buty-lw1800p,id139.html", "", "ŁSZ"),
 ("https://umstahl.pl/laweczka-wolnostojaca-z-polka-na-buty-lw2000p,id140.html", "", "ŁSZ"),
 ("https://umstahl.pl/lawko-wieszak-jednostronny-lwws1200,id389.html", "", "ŁSZ"),
 ("https://umstahl.pl/lawko-wieszak-jednostronny-lwws1650,id390.html", "", "ŁSZ"),
 ("https://umstahl.pl/lawko-wieszak-jednostronny-lwwo1000,id386.html", "794", "ŁSZ 1"),
 ("https://umstahl.pl/lawko-wieszak-jednostronny-lwwo1500,id387.html", "1066", "ŁSZ 1A"),
 ("https://umstahl.pl/lawko-wieszak-jednostronny-lwwo2000,id388.html", "", "ŁSZ"),
 ("https://umstahl.pl/lawko-wieszak-jednostronny-z-polka-lwwop1000,id391.html", "", "ŁSZ"),
 ("https://umstahl.pl/lawko-wieszak-jednostronny-z-polka-lwwop1500,id392.html", "", "ŁSZ"),
 ("https://umstahl.pl/lawko-wieszak-jednostronny-z-polka-lwwop2000,id393.html", "", "ŁSZ"),
 ("https://umstahl.pl/zestaw-szatniowy-ze-skrytkami-zls2950,id395.html", "", "SZOS"),
 ("https://umstahl.pl/zestaw-szatniowy-ze-skrytkami-zls21250,id394.html", "", "SZOS"),
 ("https://umstahl.pl/zestaw-szatniowy-ze-skrytkami-zls31250,id396.html", "", "SZOS"),
 ("https://umstahl.pl/zestaw-szatniowy-ze-skrytkami-zls5950,id397.html", "", "SZOS"),
 ("https://umstahl.pl/zestaw-szatniowy-ze-skrytkami-zls71250,id398.html", "", "SZOS"),
 # Meble socjalne » Pojemniki do segregacji odpadów
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-3-komorowy-psg3-p3-mag,id1013.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-2-komorowy-psg2-p2-mag,id1012.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-2-komorowy-psg2-w2exp,id863.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-3-komorowy-psgn3-p3,id1002.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-2-komorowy-psgn2-p2,id1001.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-3-komorowy-psgn3-w3,id1000.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-2-komorowy-psgn2-w2,id999.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-2-komorowy-psg2-p2,id429.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-5-komorowy-psg5-p5,id774.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-5-komorowy-psg5-w5,id773.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-3-komorowy-psg3-p3,id432.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-1-komorowy-psg1-p1,id426.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-4-komorowy-psg4-p4,id437.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-1-komorowy-psg1-w1,id427.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-2-komorowy-psg2-w2,id430.html", "", "MPO "),
 ("https://umstahl.pl/pojemnik-3-komorowy-z-3-ramkami-na-worek-psg3-w3,id434.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-4-komorowy-psg4-w4,id439.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-1-komorowy-duzy-psg-dw1,id425.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-2-komorowy-psg2-p1w1,id428.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-3-komorowy-psg3-p2w1,id431.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-3-komorowy-psg3-w2p1,id433.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-4-komorowy-psg4-p2w2,id435.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-4-komorowy-psg4-p3w1,id436.html", "", "MPO "),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-4-komorowy-psg4-w3p1,id438.html", "", "MPO "),
]

links = [
 ("https://umstahl.pl/metalowa-szafa-ubraniowa-sle-30r2,id403.html", "1102", "Sul 32 W"),
 ("https://umstahl.pl/metalowy-pojemnik-do-segregacji-odpadow-4-komorowy-psg4-w3p1,id438.html", "", "MPO "),
]